// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

public interface CartQueueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.CartQueue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
   * @return Whether the resource field is set.
   */
  boolean hasResource();
  /**
   * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
   * @return The resource.
   */
  com.ai.procyon.grpc.common.ObjectRef getResource();
  /**
   * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
   */
  com.ai.procyon.grpc.common.ObjectRefOrBuilder getResourceOrBuilder();

  /**
   * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
   * @return Whether the roles field is set.
   */
  boolean hasRoles();
  /**
   * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
   * @return The roles.
   */
  com.ai.procyon.grpc.common.References getRoles();
  /**
   * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
   */
  com.ai.procyon.grpc.common.ReferencesOrBuilder getRolesOrBuilder();

  /**
   * <code>string Principal = 3;</code>
   * @return The principal.
   */
  java.lang.String getPrincipal();
  /**
   * <code>string Principal = 3;</code>
   * @return The bytes for principal.
   */
  com.google.protobuf.ByteString
      getPrincipalBytes();
}
