// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

/**
 * Protobuf type {@code model.CartQueue}
 */
public final class CartQueue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.CartQueue)
    CartQueueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CartQueue.newBuilder() to construct.
  private CartQueue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CartQueue() {
    principal_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CartQueue();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CartQueue(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.ai.procyon.grpc.common.ObjectRef.Builder subBuilder = null;
            if (resource_ != null) {
              subBuilder = resource_.toBuilder();
            }
            resource_ = input.readMessage(com.ai.procyon.grpc.common.ObjectRef.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resource_);
              resource_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.ai.procyon.grpc.common.References.Builder subBuilder = null;
            if (roles_ != null) {
              subBuilder = roles_.toBuilder();
            }
            roles_ = input.readMessage(com.ai.procyon.grpc.common.References.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(roles_);
              roles_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            principal_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ai.procyon.grpc.common.CommonProto.internal_static_model_CartQueue_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ai.procyon.grpc.common.CommonProto.internal_static_model_CartQueue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ai.procyon.grpc.common.CartQueue.class, com.ai.procyon.grpc.common.CartQueue.Builder.class);
  }

  public static final int RESOURCE_FIELD_NUMBER = 1;
  private com.ai.procyon.grpc.common.ObjectRef resource_;
  /**
   * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
   * @return Whether the resource field is set.
   */
  @java.lang.Override
  public boolean hasResource() {
    return resource_ != null;
  }
  /**
   * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
   * @return The resource.
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.ObjectRef getResource() {
    return resource_ == null ? com.ai.procyon.grpc.common.ObjectRef.getDefaultInstance() : resource_;
  }
  /**
   * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.ObjectRefOrBuilder getResourceOrBuilder() {
    return getResource();
  }

  public static final int ROLES_FIELD_NUMBER = 2;
  private com.ai.procyon.grpc.common.References roles_;
  /**
   * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
   * @return Whether the roles field is set.
   */
  @java.lang.Override
  public boolean hasRoles() {
    return roles_ != null;
  }
  /**
   * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
   * @return The roles.
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.References getRoles() {
    return roles_ == null ? com.ai.procyon.grpc.common.References.getDefaultInstance() : roles_;
  }
  /**
   * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.ReferencesOrBuilder getRolesOrBuilder() {
    return getRoles();
  }

  public static final int PRINCIPAL_FIELD_NUMBER = 3;
  private volatile java.lang.Object principal_;
  /**
   * <code>string Principal = 3;</code>
   * @return The principal.
   */
  @java.lang.Override
  public java.lang.String getPrincipal() {
    java.lang.Object ref = principal_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      principal_ = s;
      return s;
    }
  }
  /**
   * <code>string Principal = 3;</code>
   * @return The bytes for principal.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPrincipalBytes() {
    java.lang.Object ref = principal_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      principal_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resource_ != null) {
      output.writeMessage(1, getResource());
    }
    if (roles_ != null) {
      output.writeMessage(2, getRoles());
    }
    if (!getPrincipalBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, principal_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resource_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResource());
    }
    if (roles_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRoles());
    }
    if (!getPrincipalBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, principal_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ai.procyon.grpc.common.CartQueue)) {
      return super.equals(obj);
    }
    com.ai.procyon.grpc.common.CartQueue other = (com.ai.procyon.grpc.common.CartQueue) obj;

    if (hasResource() != other.hasResource()) return false;
    if (hasResource()) {
      if (!getResource()
          .equals(other.getResource())) return false;
    }
    if (hasRoles() != other.hasRoles()) return false;
    if (hasRoles()) {
      if (!getRoles()
          .equals(other.getRoles())) return false;
    }
    if (!getPrincipal()
        .equals(other.getPrincipal())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResource()) {
      hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getResource().hashCode();
    }
    if (hasRoles()) {
      hash = (37 * hash) + ROLES_FIELD_NUMBER;
      hash = (53 * hash) + getRoles().hashCode();
    }
    hash = (37 * hash) + PRINCIPAL_FIELD_NUMBER;
    hash = (53 * hash) + getPrincipal().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ai.procyon.grpc.common.CartQueue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.CartQueue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.CartQueue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.CartQueue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.CartQueue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.CartQueue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.CartQueue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.CartQueue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.CartQueue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.CartQueue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.CartQueue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.CartQueue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ai.procyon.grpc.common.CartQueue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.CartQueue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.CartQueue)
      com.ai.procyon.grpc.common.CartQueueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_CartQueue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_CartQueue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ai.procyon.grpc.common.CartQueue.class, com.ai.procyon.grpc.common.CartQueue.Builder.class);
    }

    // Construct using com.ai.procyon.grpc.common.CartQueue.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (resourceBuilder_ == null) {
        resource_ = null;
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }
      if (rolesBuilder_ == null) {
        roles_ = null;
      } else {
        roles_ = null;
        rolesBuilder_ = null;
      }
      principal_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_CartQueue_descriptor;
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.CartQueue getDefaultInstanceForType() {
      return com.ai.procyon.grpc.common.CartQueue.getDefaultInstance();
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.CartQueue build() {
      com.ai.procyon.grpc.common.CartQueue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.CartQueue buildPartial() {
      com.ai.procyon.grpc.common.CartQueue result = new com.ai.procyon.grpc.common.CartQueue(this);
      if (resourceBuilder_ == null) {
        result.resource_ = resource_;
      } else {
        result.resource_ = resourceBuilder_.build();
      }
      if (rolesBuilder_ == null) {
        result.roles_ = roles_;
      } else {
        result.roles_ = rolesBuilder_.build();
      }
      result.principal_ = principal_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ai.procyon.grpc.common.CartQueue) {
        return mergeFrom((com.ai.procyon.grpc.common.CartQueue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ai.procyon.grpc.common.CartQueue other) {
      if (other == com.ai.procyon.grpc.common.CartQueue.getDefaultInstance()) return this;
      if (other.hasResource()) {
        mergeResource(other.getResource());
      }
      if (other.hasRoles()) {
        mergeRoles(other.getRoles());
      }
      if (!other.getPrincipal().isEmpty()) {
        principal_ = other.principal_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ai.procyon.grpc.common.CartQueue parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ai.procyon.grpc.common.CartQueue) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.ai.procyon.grpc.common.ObjectRef resource_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ai.procyon.grpc.common.ObjectRef, com.ai.procyon.grpc.common.ObjectRef.Builder, com.ai.procyon.grpc.common.ObjectRefOrBuilder> resourceBuilder_;
    /**
     * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the resource field is set.
     */
    public boolean hasResource() {
      return resourceBuilder_ != null || resource_ != null;
    }
    /**
     * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
     * @return The resource.
     */
    public com.ai.procyon.grpc.common.ObjectRef getResource() {
      if (resourceBuilder_ == null) {
        return resource_ == null ? com.ai.procyon.grpc.common.ObjectRef.getDefaultInstance() : resource_;
      } else {
        return resourceBuilder_.getMessage();
      }
    }
    /**
     * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder setResource(com.ai.procyon.grpc.common.ObjectRef value) {
      if (resourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        resourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder setResource(
        com.ai.procyon.grpc.common.ObjectRef.Builder builderForValue) {
      if (resourceBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        resourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder mergeResource(com.ai.procyon.grpc.common.ObjectRef value) {
      if (resourceBuilder_ == null) {
        if (resource_ != null) {
          resource_ =
            com.ai.procyon.grpc.common.ObjectRef.newBuilder(resource_).mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        resourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder clearResource() {
      if (resourceBuilder_ == null) {
        resource_ = null;
        onChanged();
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
     */
    public com.ai.procyon.grpc.common.ObjectRef.Builder getResourceBuilder() {
      
      onChanged();
      return getResourceFieldBuilder().getBuilder();
    }
    /**
     * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
     */
    public com.ai.procyon.grpc.common.ObjectRefOrBuilder getResourceOrBuilder() {
      if (resourceBuilder_ != null) {
        return resourceBuilder_.getMessageOrBuilder();
      } else {
        return resource_ == null ?
            com.ai.procyon.grpc.common.ObjectRef.getDefaultInstance() : resource_;
      }
    }
    /**
     * <code>.model.ObjectRef Resource = 1 [(.gogoproto.nullable) = false];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ai.procyon.grpc.common.ObjectRef, com.ai.procyon.grpc.common.ObjectRef.Builder, com.ai.procyon.grpc.common.ObjectRefOrBuilder> 
        getResourceFieldBuilder() {
      if (resourceBuilder_ == null) {
        resourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ai.procyon.grpc.common.ObjectRef, com.ai.procyon.grpc.common.ObjectRef.Builder, com.ai.procyon.grpc.common.ObjectRefOrBuilder>(
                getResource(),
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      return resourceBuilder_;
    }

    private com.ai.procyon.grpc.common.References roles_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ai.procyon.grpc.common.References, com.ai.procyon.grpc.common.References.Builder, com.ai.procyon.grpc.common.ReferencesOrBuilder> rolesBuilder_;
    /**
     * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     * @return Whether the roles field is set.
     */
    public boolean hasRoles() {
      return rolesBuilder_ != null || roles_ != null;
    }
    /**
     * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     * @return The roles.
     */
    public com.ai.procyon.grpc.common.References getRoles() {
      if (rolesBuilder_ == null) {
        return roles_ == null ? com.ai.procyon.grpc.common.References.getDefaultInstance() : roles_;
      } else {
        return rolesBuilder_.getMessage();
      }
    }
    /**
     * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     */
    public Builder setRoles(com.ai.procyon.grpc.common.References value) {
      if (rolesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        roles_ = value;
        onChanged();
      } else {
        rolesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     */
    public Builder setRoles(
        com.ai.procyon.grpc.common.References.Builder builderForValue) {
      if (rolesBuilder_ == null) {
        roles_ = builderForValue.build();
        onChanged();
      } else {
        rolesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     */
    public Builder mergeRoles(com.ai.procyon.grpc.common.References value) {
      if (rolesBuilder_ == null) {
        if (roles_ != null) {
          roles_ =
            com.ai.procyon.grpc.common.References.newBuilder(roles_).mergeFrom(value).buildPartial();
        } else {
          roles_ = value;
        }
        onChanged();
      } else {
        rolesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     */
    public Builder clearRoles() {
      if (rolesBuilder_ == null) {
        roles_ = null;
        onChanged();
      } else {
        roles_ = null;
        rolesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     */
    public com.ai.procyon.grpc.common.References.Builder getRolesBuilder() {
      
      onChanged();
      return getRolesFieldBuilder().getBuilder();
    }
    /**
     * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     */
    public com.ai.procyon.grpc.common.ReferencesOrBuilder getRolesOrBuilder() {
      if (rolesBuilder_ != null) {
        return rolesBuilder_.getMessageOrBuilder();
      } else {
        return roles_ == null ?
            com.ai.procyon.grpc.common.References.getDefaultInstance() : roles_;
      }
    }
    /**
     * <code>.model.References Roles = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ai.procyon.grpc.common.References, com.ai.procyon.grpc.common.References.Builder, com.ai.procyon.grpc.common.ReferencesOrBuilder> 
        getRolesFieldBuilder() {
      if (rolesBuilder_ == null) {
        rolesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ai.procyon.grpc.common.References, com.ai.procyon.grpc.common.References.Builder, com.ai.procyon.grpc.common.ReferencesOrBuilder>(
                getRoles(),
                getParentForChildren(),
                isClean());
        roles_ = null;
      }
      return rolesBuilder_;
    }

    private java.lang.Object principal_ = "";
    /**
     * <code>string Principal = 3;</code>
     * @return The principal.
     */
    public java.lang.String getPrincipal() {
      java.lang.Object ref = principal_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        principal_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Principal = 3;</code>
     * @return The bytes for principal.
     */
    public com.google.protobuf.ByteString
        getPrincipalBytes() {
      java.lang.Object ref = principal_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        principal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Principal = 3;</code>
     * @param value The principal to set.
     * @return This builder for chaining.
     */
    public Builder setPrincipal(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      principal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Principal = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrincipal() {
      
      principal_ = getDefaultInstance().getPrincipal();
      onChanged();
      return this;
    }
    /**
     * <code>string Principal = 3;</code>
     * @param value The bytes for principal to set.
     * @return This builder for chaining.
     */
    public Builder setPrincipalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      principal_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.CartQueue)
  }

  // @@protoc_insertion_point(class_scope:model.CartQueue)
  private static final com.ai.procyon.grpc.common.CartQueue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ai.procyon.grpc.common.CartQueue();
  }

  public static com.ai.procyon.grpc.common.CartQueue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CartQueue>
      PARSER = new com.google.protobuf.AbstractParser<CartQueue>() {
    @java.lang.Override
    public CartQueue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CartQueue(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CartQueue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CartQueue> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ai.procyon.grpc.common.CartQueue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

