// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common.proto

package com.ai.procyon.grpc.common;

/**
* Validates {@code GcpServiceAccountSpec} protobuf objects.
*/
public class GcpServiceAccountSpecValidator implements io.envoyproxy.pgv.ValidatorImpl<com.ai.procyon.grpc.common.GcpServiceAccountSpec>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(com.ai.procyon.grpc.common.GcpServiceAccountSpec.class)) return new GcpServiceAccountSpecValidator();
		
		return null;
	}
		
	
		
	
		
	
	

	public void assertValid(com.ai.procyon.grpc.common.GcpServiceAccountSpec proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			// Validate Project
			if (proto.hasProject()) index.validatorFor(proto.getProject()).assertValid(proto.getProject());
	// no validation rules for Name

	// no validation rules for Description

	
	}

}

