// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

/**
 * <pre>
 * github Member
 * </pre>
 *
 * Protobuf type {@code model.GithubMember}
 */
public final class GithubMember extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.GithubMember)
    GithubMemberOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GithubMember.newBuilder() to construct.
  private GithubMember(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GithubMember() {
    managedBy_ = "";
    role_ = "";
    status_ = "";
    permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    scimProvisonedIdentity_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GithubMember();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GithubMember(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.ai.procyon.grpc.common.ObjectRef.Builder subBuilder = null;
            if (memberRef_ != null) {
              subBuilder = memberRef_.toBuilder();
            }
            memberRef_ = input.readMessage(com.ai.procyon.grpc.common.ObjectRef.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(memberRef_);
              memberRef_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            managedBy_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            role_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              permissions_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            permissions_.add(s);
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            scimProvisonedIdentity_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        permissions_ = permissions_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ai.procyon.grpc.common.CommonProto.internal_static_model_GithubMember_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ai.procyon.grpc.common.CommonProto.internal_static_model_GithubMember_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ai.procyon.grpc.common.GithubMember.class, com.ai.procyon.grpc.common.GithubMember.Builder.class);
  }

  public static final int MEMBERREF_FIELD_NUMBER = 1;
  private com.ai.procyon.grpc.common.ObjectRef memberRef_;
  /**
   * <code>.model.ObjectRef memberRef = 1 [(.gogoproto.nullable) = false];</code>
   * @return Whether the memberRef field is set.
   */
  @java.lang.Override
  public boolean hasMemberRef() {
    return memberRef_ != null;
  }
  /**
   * <code>.model.ObjectRef memberRef = 1 [(.gogoproto.nullable) = false];</code>
   * @return The memberRef.
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.ObjectRef getMemberRef() {
    return memberRef_ == null ? com.ai.procyon.grpc.common.ObjectRef.getDefaultInstance() : memberRef_;
  }
  /**
   * <code>.model.ObjectRef memberRef = 1 [(.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.ObjectRefOrBuilder getMemberRefOrBuilder() {
    return getMemberRef();
  }

  public static final int MANAGEDBY_FIELD_NUMBER = 2;
  private volatile java.lang.Object managedBy_;
  /**
   * <code>string ManagedBy = 2;</code>
   * @return The managedBy.
   */
  @java.lang.Override
  public java.lang.String getManagedBy() {
    java.lang.Object ref = managedBy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      managedBy_ = s;
      return s;
    }
  }
  /**
   * <code>string ManagedBy = 2;</code>
   * @return The bytes for managedBy.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getManagedByBytes() {
    java.lang.Object ref = managedBy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      managedBy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLE_FIELD_NUMBER = 3;
  private volatile java.lang.Object role_;
  /**
   * <code>string Role = 3;</code>
   * @return The role.
   */
  @java.lang.Override
  public java.lang.String getRole() {
    java.lang.Object ref = role_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      role_ = s;
      return s;
    }
  }
  /**
   * <code>string Role = 3;</code>
   * @return The bytes for role.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoleBytes() {
    java.lang.Object ref = role_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      role_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private volatile java.lang.Object status_;
  /**
   * <code>string Status = 4;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string Status = 4;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERMISSIONS_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList permissions_;
  /**
   * <code>repeated string Permissions = 5;</code>
   * @return A list containing the permissions.
   */
  public com.google.protobuf.ProtocolStringList
      getPermissionsList() {
    return permissions_;
  }
  /**
   * <code>repeated string Permissions = 5;</code>
   * @return The count of permissions.
   */
  public int getPermissionsCount() {
    return permissions_.size();
  }
  /**
   * <code>repeated string Permissions = 5;</code>
   * @param index The index of the element to return.
   * @return The permissions at the given index.
   */
  public java.lang.String getPermissions(int index) {
    return permissions_.get(index);
  }
  /**
   * <code>repeated string Permissions = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the permissions at the given index.
   */
  public com.google.protobuf.ByteString
      getPermissionsBytes(int index) {
    return permissions_.getByteString(index);
  }

  public static final int SCIMPROVISONEDIDENTITY_FIELD_NUMBER = 6;
  private volatile java.lang.Object scimProvisonedIdentity_;
  /**
   * <code>string ScimProvisonedIdentity = 6;</code>
   * @return The scimProvisonedIdentity.
   */
  @java.lang.Override
  public java.lang.String getScimProvisonedIdentity() {
    java.lang.Object ref = scimProvisonedIdentity_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scimProvisonedIdentity_ = s;
      return s;
    }
  }
  /**
   * <code>string ScimProvisonedIdentity = 6;</code>
   * @return The bytes for scimProvisonedIdentity.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScimProvisonedIdentityBytes() {
    java.lang.Object ref = scimProvisonedIdentity_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scimProvisonedIdentity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (memberRef_ != null) {
      output.writeMessage(1, getMemberRef());
    }
    if (!getManagedByBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, managedBy_);
    }
    if (!getRoleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, role_);
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, status_);
    }
    for (int i = 0; i < permissions_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, permissions_.getRaw(i));
    }
    if (!getScimProvisonedIdentityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, scimProvisonedIdentity_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (memberRef_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMemberRef());
    }
    if (!getManagedByBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, managedBy_);
    }
    if (!getRoleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, role_);
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, status_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < permissions_.size(); i++) {
        dataSize += computeStringSizeNoTag(permissions_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPermissionsList().size();
    }
    if (!getScimProvisonedIdentityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, scimProvisonedIdentity_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ai.procyon.grpc.common.GithubMember)) {
      return super.equals(obj);
    }
    com.ai.procyon.grpc.common.GithubMember other = (com.ai.procyon.grpc.common.GithubMember) obj;

    if (hasMemberRef() != other.hasMemberRef()) return false;
    if (hasMemberRef()) {
      if (!getMemberRef()
          .equals(other.getMemberRef())) return false;
    }
    if (!getManagedBy()
        .equals(other.getManagedBy())) return false;
    if (!getRole()
        .equals(other.getRole())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getPermissionsList()
        .equals(other.getPermissionsList())) return false;
    if (!getScimProvisonedIdentity()
        .equals(other.getScimProvisonedIdentity())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMemberRef()) {
      hash = (37 * hash) + MEMBERREF_FIELD_NUMBER;
      hash = (53 * hash) + getMemberRef().hashCode();
    }
    hash = (37 * hash) + MANAGEDBY_FIELD_NUMBER;
    hash = (53 * hash) + getManagedBy().hashCode();
    hash = (37 * hash) + ROLE_FIELD_NUMBER;
    hash = (53 * hash) + getRole().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    if (getPermissionsCount() > 0) {
      hash = (37 * hash) + PERMISSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getPermissionsList().hashCode();
    }
    hash = (37 * hash) + SCIMPROVISONEDIDENTITY_FIELD_NUMBER;
    hash = (53 * hash) + getScimProvisonedIdentity().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ai.procyon.grpc.common.GithubMember parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.GithubMember parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.GithubMember parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.GithubMember parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.GithubMember parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.GithubMember parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.GithubMember parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.GithubMember parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.GithubMember parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.GithubMember parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.GithubMember parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.GithubMember parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ai.procyon.grpc.common.GithubMember prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * github Member
   * </pre>
   *
   * Protobuf type {@code model.GithubMember}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.GithubMember)
      com.ai.procyon.grpc.common.GithubMemberOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_GithubMember_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_GithubMember_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ai.procyon.grpc.common.GithubMember.class, com.ai.procyon.grpc.common.GithubMember.Builder.class);
    }

    // Construct using com.ai.procyon.grpc.common.GithubMember.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (memberRefBuilder_ == null) {
        memberRef_ = null;
      } else {
        memberRef_ = null;
        memberRefBuilder_ = null;
      }
      managedBy_ = "";

      role_ = "";

      status_ = "";

      permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      scimProvisonedIdentity_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_GithubMember_descriptor;
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.GithubMember getDefaultInstanceForType() {
      return com.ai.procyon.grpc.common.GithubMember.getDefaultInstance();
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.GithubMember build() {
      com.ai.procyon.grpc.common.GithubMember result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.GithubMember buildPartial() {
      com.ai.procyon.grpc.common.GithubMember result = new com.ai.procyon.grpc.common.GithubMember(this);
      int from_bitField0_ = bitField0_;
      if (memberRefBuilder_ == null) {
        result.memberRef_ = memberRef_;
      } else {
        result.memberRef_ = memberRefBuilder_.build();
      }
      result.managedBy_ = managedBy_;
      result.role_ = role_;
      result.status_ = status_;
      if (((bitField0_ & 0x00000001) != 0)) {
        permissions_ = permissions_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.permissions_ = permissions_;
      result.scimProvisonedIdentity_ = scimProvisonedIdentity_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ai.procyon.grpc.common.GithubMember) {
        return mergeFrom((com.ai.procyon.grpc.common.GithubMember)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ai.procyon.grpc.common.GithubMember other) {
      if (other == com.ai.procyon.grpc.common.GithubMember.getDefaultInstance()) return this;
      if (other.hasMemberRef()) {
        mergeMemberRef(other.getMemberRef());
      }
      if (!other.getManagedBy().isEmpty()) {
        managedBy_ = other.managedBy_;
        onChanged();
      }
      if (!other.getRole().isEmpty()) {
        role_ = other.role_;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (!other.permissions_.isEmpty()) {
        if (permissions_.isEmpty()) {
          permissions_ = other.permissions_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensurePermissionsIsMutable();
          permissions_.addAll(other.permissions_);
        }
        onChanged();
      }
      if (!other.getScimProvisonedIdentity().isEmpty()) {
        scimProvisonedIdentity_ = other.scimProvisonedIdentity_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ai.procyon.grpc.common.GithubMember parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ai.procyon.grpc.common.GithubMember) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.ai.procyon.grpc.common.ObjectRef memberRef_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ai.procyon.grpc.common.ObjectRef, com.ai.procyon.grpc.common.ObjectRef.Builder, com.ai.procyon.grpc.common.ObjectRefOrBuilder> memberRefBuilder_;
    /**
     * <code>.model.ObjectRef memberRef = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the memberRef field is set.
     */
    public boolean hasMemberRef() {
      return memberRefBuilder_ != null || memberRef_ != null;
    }
    /**
     * <code>.model.ObjectRef memberRef = 1 [(.gogoproto.nullable) = false];</code>
     * @return The memberRef.
     */
    public com.ai.procyon.grpc.common.ObjectRef getMemberRef() {
      if (memberRefBuilder_ == null) {
        return memberRef_ == null ? com.ai.procyon.grpc.common.ObjectRef.getDefaultInstance() : memberRef_;
      } else {
        return memberRefBuilder_.getMessage();
      }
    }
    /**
     * <code>.model.ObjectRef memberRef = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder setMemberRef(com.ai.procyon.grpc.common.ObjectRef value) {
      if (memberRefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        memberRef_ = value;
        onChanged();
      } else {
        memberRefBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.model.ObjectRef memberRef = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder setMemberRef(
        com.ai.procyon.grpc.common.ObjectRef.Builder builderForValue) {
      if (memberRefBuilder_ == null) {
        memberRef_ = builderForValue.build();
        onChanged();
      } else {
        memberRefBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.model.ObjectRef memberRef = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder mergeMemberRef(com.ai.procyon.grpc.common.ObjectRef value) {
      if (memberRefBuilder_ == null) {
        if (memberRef_ != null) {
          memberRef_ =
            com.ai.procyon.grpc.common.ObjectRef.newBuilder(memberRef_).mergeFrom(value).buildPartial();
        } else {
          memberRef_ = value;
        }
        onChanged();
      } else {
        memberRefBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.model.ObjectRef memberRef = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder clearMemberRef() {
      if (memberRefBuilder_ == null) {
        memberRef_ = null;
        onChanged();
      } else {
        memberRef_ = null;
        memberRefBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.model.ObjectRef memberRef = 1 [(.gogoproto.nullable) = false];</code>
     */
    public com.ai.procyon.grpc.common.ObjectRef.Builder getMemberRefBuilder() {
      
      onChanged();
      return getMemberRefFieldBuilder().getBuilder();
    }
    /**
     * <code>.model.ObjectRef memberRef = 1 [(.gogoproto.nullable) = false];</code>
     */
    public com.ai.procyon.grpc.common.ObjectRefOrBuilder getMemberRefOrBuilder() {
      if (memberRefBuilder_ != null) {
        return memberRefBuilder_.getMessageOrBuilder();
      } else {
        return memberRef_ == null ?
            com.ai.procyon.grpc.common.ObjectRef.getDefaultInstance() : memberRef_;
      }
    }
    /**
     * <code>.model.ObjectRef memberRef = 1 [(.gogoproto.nullable) = false];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ai.procyon.grpc.common.ObjectRef, com.ai.procyon.grpc.common.ObjectRef.Builder, com.ai.procyon.grpc.common.ObjectRefOrBuilder> 
        getMemberRefFieldBuilder() {
      if (memberRefBuilder_ == null) {
        memberRefBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ai.procyon.grpc.common.ObjectRef, com.ai.procyon.grpc.common.ObjectRef.Builder, com.ai.procyon.grpc.common.ObjectRefOrBuilder>(
                getMemberRef(),
                getParentForChildren(),
                isClean());
        memberRef_ = null;
      }
      return memberRefBuilder_;
    }

    private java.lang.Object managedBy_ = "";
    /**
     * <code>string ManagedBy = 2;</code>
     * @return The managedBy.
     */
    public java.lang.String getManagedBy() {
      java.lang.Object ref = managedBy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        managedBy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ManagedBy = 2;</code>
     * @return The bytes for managedBy.
     */
    public com.google.protobuf.ByteString
        getManagedByBytes() {
      java.lang.Object ref = managedBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        managedBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ManagedBy = 2;</code>
     * @param value The managedBy to set.
     * @return This builder for chaining.
     */
    public Builder setManagedBy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      managedBy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ManagedBy = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearManagedBy() {
      
      managedBy_ = getDefaultInstance().getManagedBy();
      onChanged();
      return this;
    }
    /**
     * <code>string ManagedBy = 2;</code>
     * @param value The bytes for managedBy to set.
     * @return This builder for chaining.
     */
    public Builder setManagedByBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      managedBy_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object role_ = "";
    /**
     * <code>string Role = 3;</code>
     * @return The role.
     */
    public java.lang.String getRole() {
      java.lang.Object ref = role_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        role_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Role = 3;</code>
     * @return The bytes for role.
     */
    public com.google.protobuf.ByteString
        getRoleBytes() {
      java.lang.Object ref = role_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        role_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Role = 3;</code>
     * @param value The role to set.
     * @return This builder for chaining.
     */
    public Builder setRole(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      role_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Role = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRole() {
      
      role_ = getDefaultInstance().getRole();
      onChanged();
      return this;
    }
    /**
     * <code>string Role = 3;</code>
     * @param value The bytes for role to set.
     * @return This builder for chaining.
     */
    public Builder setRoleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      role_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string Status = 4;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Status = 4;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Status = 4;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Status = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string Status = 4;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensurePermissionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        permissions_ = new com.google.protobuf.LazyStringArrayList(permissions_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string Permissions = 5;</code>
     * @return A list containing the permissions.
     */
    public com.google.protobuf.ProtocolStringList
        getPermissionsList() {
      return permissions_.getUnmodifiableView();
    }
    /**
     * <code>repeated string Permissions = 5;</code>
     * @return The count of permissions.
     */
    public int getPermissionsCount() {
      return permissions_.size();
    }
    /**
     * <code>repeated string Permissions = 5;</code>
     * @param index The index of the element to return.
     * @return The permissions at the given index.
     */
    public java.lang.String getPermissions(int index) {
      return permissions_.get(index);
    }
    /**
     * <code>repeated string Permissions = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the permissions at the given index.
     */
    public com.google.protobuf.ByteString
        getPermissionsBytes(int index) {
      return permissions_.getByteString(index);
    }
    /**
     * <code>repeated string Permissions = 5;</code>
     * @param index The index to set the value at.
     * @param value The permissions to set.
     * @return This builder for chaining.
     */
    public Builder setPermissions(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePermissionsIsMutable();
      permissions_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Permissions = 5;</code>
     * @param value The permissions to add.
     * @return This builder for chaining.
     */
    public Builder addPermissions(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePermissionsIsMutable();
      permissions_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Permissions = 5;</code>
     * @param values The permissions to add.
     * @return This builder for chaining.
     */
    public Builder addAllPermissions(
        java.lang.Iterable<java.lang.String> values) {
      ensurePermissionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, permissions_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Permissions = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPermissions() {
      permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Permissions = 5;</code>
     * @param value The bytes of the permissions to add.
     * @return This builder for chaining.
     */
    public Builder addPermissionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensurePermissionsIsMutable();
      permissions_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object scimProvisonedIdentity_ = "";
    /**
     * <code>string ScimProvisonedIdentity = 6;</code>
     * @return The scimProvisonedIdentity.
     */
    public java.lang.String getScimProvisonedIdentity() {
      java.lang.Object ref = scimProvisonedIdentity_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scimProvisonedIdentity_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ScimProvisonedIdentity = 6;</code>
     * @return The bytes for scimProvisonedIdentity.
     */
    public com.google.protobuf.ByteString
        getScimProvisonedIdentityBytes() {
      java.lang.Object ref = scimProvisonedIdentity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scimProvisonedIdentity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ScimProvisonedIdentity = 6;</code>
     * @param value The scimProvisonedIdentity to set.
     * @return This builder for chaining.
     */
    public Builder setScimProvisonedIdentity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      scimProvisonedIdentity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ScimProvisonedIdentity = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearScimProvisonedIdentity() {
      
      scimProvisonedIdentity_ = getDefaultInstance().getScimProvisonedIdentity();
      onChanged();
      return this;
    }
    /**
     * <code>string ScimProvisonedIdentity = 6;</code>
     * @param value The bytes for scimProvisonedIdentity to set.
     * @return This builder for chaining.
     */
    public Builder setScimProvisonedIdentityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      scimProvisonedIdentity_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.GithubMember)
  }

  // @@protoc_insertion_point(class_scope:model.GithubMember)
  private static final com.ai.procyon.grpc.common.GithubMember DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ai.procyon.grpc.common.GithubMember();
  }

  public static com.ai.procyon.grpc.common.GithubMember getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GithubMember>
      PARSER = new com.google.protobuf.AbstractParser<GithubMember>() {
    @java.lang.Override
    public GithubMember parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GithubMember(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GithubMember> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GithubMember> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ai.procyon.grpc.common.GithubMember getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

