// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common.proto

package com.ai.procyon.grpc.common;

/**
* Validates {@code MFAResponse} protobuf objects.
*/
public class MFAResponseValidator implements io.envoyproxy.pgv.ValidatorImpl<com.ai.procyon.grpc.common.MFAResponse>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(com.ai.procyon.grpc.common.MFAResponse.class)) return new MFAResponseValidator();
		
		return null;
	}
		
	
		
	
	

	public void assertValid(com.ai.procyon.grpc.common.MFAResponse proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for ResponseTime

	// no validation rules for Response

	
	}

}

