// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

public interface ObjectRefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.ObjectRef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string RefKind = 1;</code>
   * @return The refKind.
   */
  java.lang.String getRefKind();
  /**
   * <code>string RefKind = 1;</code>
   * @return The bytes for refKind.
   */
  com.google.protobuf.ByteString
      getRefKindBytes();

  /**
   * <code>uint64 RefID = 2;</code>
   * @return The refID.
   */
  long getRefID();
}
