// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

public interface ObjStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.ObjStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string Status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string Error = 2;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string Error = 2;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>string State = 3;</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>string State = 3;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();
}
