// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

public interface PolicyRulesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.PolicyRules)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .model.PolicyRule PolicyRule = 1;</code>
   */
  java.util.List<com.ai.procyon.grpc.common.PolicyRule> 
      getPolicyRuleList();
  /**
   * <code>repeated .model.PolicyRule PolicyRule = 1;</code>
   */
  com.ai.procyon.grpc.common.PolicyRule getPolicyRule(int index);
  /**
   * <code>repeated .model.PolicyRule PolicyRule = 1;</code>
   */
  int getPolicyRuleCount();
  /**
   * <code>repeated .model.PolicyRule PolicyRule = 1;</code>
   */
  java.util.List<? extends com.ai.procyon.grpc.common.PolicyRuleOrBuilder> 
      getPolicyRuleOrBuilderList();
  /**
   * <code>repeated .model.PolicyRule PolicyRule = 1;</code>
   */
  com.ai.procyon.grpc.common.PolicyRuleOrBuilder getPolicyRuleOrBuilder(
      int index);
}
