// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

/**
 * Protobuf type {@code model.PolicyRule}
 */
public final class PolicyRule extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.PolicyRule)
    PolicyRuleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PolicyRule.newBuilder() to construct.
  private PolicyRule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PolicyRule() {
    principal_ = "";
    roleAssignments_ = java.util.Collections.emptyList();
    aDRoleAssignments_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PolicyRule();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PolicyRule(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.ai.procyon.grpc.common.ObjectRef.Builder subBuilder = null;
            if (objectRef_ != null) {
              subBuilder = objectRef_.toBuilder();
            }
            objectRef_ = input.readMessage(com.ai.procyon.grpc.common.ObjectRef.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(objectRef_);
              objectRef_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            principal_ = s;
            break;
          }
          case 26: {
            com.ai.procyon.grpc.common.ObjectRef.Builder subBuilder = null;
            if (gcpRoleTarget_ != null) {
              subBuilder = gcpRoleTarget_.toBuilder();
            }
            gcpRoleTarget_ = input.readMessage(com.ai.procyon.grpc.common.ObjectRef.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(gcpRoleTarget_);
              gcpRoleTarget_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.ai.procyon.grpc.common.References.Builder subBuilder = null;
            if (services_ != null) {
              subBuilder = services_.toBuilder();
            }
            services_ = input.readMessage(com.ai.procyon.grpc.common.References.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(services_);
              services_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {

            procyonCreated_ = input.readBool();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              roleAssignments_ = new java.util.ArrayList<com.ai.procyon.grpc.common.RoleAssignment>();
              mutable_bitField0_ |= 0x00000001;
            }
            roleAssignments_.add(
                input.readMessage(com.ai.procyon.grpc.common.RoleAssignment.parser(), extensionRegistry));
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              aDRoleAssignments_ = new java.util.ArrayList<com.ai.procyon.grpc.common.RoleAssignment>();
              mutable_bitField0_ |= 0x00000002;
            }
            aDRoleAssignments_.add(
                input.readMessage(com.ai.procyon.grpc.common.RoleAssignment.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        roleAssignments_ = java.util.Collections.unmodifiableList(roleAssignments_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        aDRoleAssignments_ = java.util.Collections.unmodifiableList(aDRoleAssignments_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ai.procyon.grpc.common.CommonProto.internal_static_model_PolicyRule_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ai.procyon.grpc.common.CommonProto.internal_static_model_PolicyRule_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ai.procyon.grpc.common.PolicyRule.class, com.ai.procyon.grpc.common.PolicyRule.Builder.class);
  }

  public static final int OBJECTREF_FIELD_NUMBER = 1;
  private com.ai.procyon.grpc.common.ObjectRef objectRef_;
  /**
   * <code>.model.ObjectRef ObjectRef = 1 [(.gogoproto.nullable) = false];</code>
   * @return Whether the objectRef field is set.
   */
  @java.lang.Override
  public boolean hasObjectRef() {
    return objectRef_ != null;
  }
  /**
   * <code>.model.ObjectRef ObjectRef = 1 [(.gogoproto.nullable) = false];</code>
   * @return The objectRef.
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.ObjectRef getObjectRef() {
    return objectRef_ == null ? com.ai.procyon.grpc.common.ObjectRef.getDefaultInstance() : objectRef_;
  }
  /**
   * <code>.model.ObjectRef ObjectRef = 1 [(.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.ObjectRefOrBuilder getObjectRefOrBuilder() {
    return getObjectRef();
  }

  public static final int PRINCIPAL_FIELD_NUMBER = 2;
  private volatile java.lang.Object principal_;
  /**
   * <code>string Principal = 2;</code>
   * @return The principal.
   */
  @java.lang.Override
  public java.lang.String getPrincipal() {
    java.lang.Object ref = principal_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      principal_ = s;
      return s;
    }
  }
  /**
   * <code>string Principal = 2;</code>
   * @return The bytes for principal.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPrincipalBytes() {
    java.lang.Object ref = principal_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      principal_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GCPROLETARGET_FIELD_NUMBER = 3;
  private com.ai.procyon.grpc.common.ObjectRef gcpRoleTarget_;
  /**
   * <pre>
   * used only when 'ObjectRef' is a GCP role
   * </pre>
   *
   * <code>.model.ObjectRef GcpRoleTarget = 3;</code>
   * @return Whether the gcpRoleTarget field is set.
   */
  @java.lang.Override
  public boolean hasGcpRoleTarget() {
    return gcpRoleTarget_ != null;
  }
  /**
   * <pre>
   * used only when 'ObjectRef' is a GCP role
   * </pre>
   *
   * <code>.model.ObjectRef GcpRoleTarget = 3;</code>
   * @return The gcpRoleTarget.
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.ObjectRef getGcpRoleTarget() {
    return gcpRoleTarget_ == null ? com.ai.procyon.grpc.common.ObjectRef.getDefaultInstance() : gcpRoleTarget_;
  }
  /**
   * <pre>
   * used only when 'ObjectRef' is a GCP role
   * </pre>
   *
   * <code>.model.ObjectRef GcpRoleTarget = 3;</code>
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.ObjectRefOrBuilder getGcpRoleTargetOrBuilder() {
    return getGcpRoleTarget();
  }

  public static final int SERVICES_FIELD_NUMBER = 4;
  private com.ai.procyon.grpc.common.References services_;
  /**
   * <code>.model.References Services = 4 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
   * @return Whether the services field is set.
   */
  @java.lang.Override
  public boolean hasServices() {
    return services_ != null;
  }
  /**
   * <code>.model.References Services = 4 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
   * @return The services.
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.References getServices() {
    return services_ == null ? com.ai.procyon.grpc.common.References.getDefaultInstance() : services_;
  }
  /**
   * <code>.model.References Services = 4 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.ReferencesOrBuilder getServicesOrBuilder() {
    return getServices();
  }

  public static final int PROCYONCREATED_FIELD_NUMBER = 5;
  private boolean procyonCreated_;
  /**
   * <code>bool ProcyonCreated = 5;</code>
   * @return The procyonCreated.
   */
  @java.lang.Override
  public boolean getProcyonCreated() {
    return procyonCreated_;
  }

  public static final int ROLEASSIGNMENTS_FIELD_NUMBER = 6;
  private java.util.List<com.ai.procyon.grpc.common.RoleAssignment> roleAssignments_;
  /**
   * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
   */
  @java.lang.Override
  public java.util.List<com.ai.procyon.grpc.common.RoleAssignment> getRoleAssignmentsList() {
    return roleAssignments_;
  }
  /**
   * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ai.procyon.grpc.common.RoleAssignmentOrBuilder> 
      getRoleAssignmentsOrBuilderList() {
    return roleAssignments_;
  }
  /**
   * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
   */
  @java.lang.Override
  public int getRoleAssignmentsCount() {
    return roleAssignments_.size();
  }
  /**
   * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.RoleAssignment getRoleAssignments(int index) {
    return roleAssignments_.get(index);
  }
  /**
   * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.RoleAssignmentOrBuilder getRoleAssignmentsOrBuilder(
      int index) {
    return roleAssignments_.get(index);
  }

  public static final int ADROLEASSIGNMENTS_FIELD_NUMBER = 7;
  private java.util.List<com.ai.procyon.grpc.common.RoleAssignment> aDRoleAssignments_;
  /**
   * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.ai.procyon.grpc.common.RoleAssignment> getADRoleAssignmentsList() {
    return aDRoleAssignments_;
  }
  /**
   * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ai.procyon.grpc.common.RoleAssignmentOrBuilder> 
      getADRoleAssignmentsOrBuilderList() {
    return aDRoleAssignments_;
  }
  /**
   * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
   */
  @java.lang.Override
  public int getADRoleAssignmentsCount() {
    return aDRoleAssignments_.size();
  }
  /**
   * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.RoleAssignment getADRoleAssignments(int index) {
    return aDRoleAssignments_.get(index);
  }
  /**
   * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.RoleAssignmentOrBuilder getADRoleAssignmentsOrBuilder(
      int index) {
    return aDRoleAssignments_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (objectRef_ != null) {
      output.writeMessage(1, getObjectRef());
    }
    if (!getPrincipalBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, principal_);
    }
    if (gcpRoleTarget_ != null) {
      output.writeMessage(3, getGcpRoleTarget());
    }
    if (services_ != null) {
      output.writeMessage(4, getServices());
    }
    if (procyonCreated_ != false) {
      output.writeBool(5, procyonCreated_);
    }
    for (int i = 0; i < roleAssignments_.size(); i++) {
      output.writeMessage(6, roleAssignments_.get(i));
    }
    for (int i = 0; i < aDRoleAssignments_.size(); i++) {
      output.writeMessage(7, aDRoleAssignments_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (objectRef_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getObjectRef());
    }
    if (!getPrincipalBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, principal_);
    }
    if (gcpRoleTarget_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getGcpRoleTarget());
    }
    if (services_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getServices());
    }
    if (procyonCreated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, procyonCreated_);
    }
    for (int i = 0; i < roleAssignments_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, roleAssignments_.get(i));
    }
    for (int i = 0; i < aDRoleAssignments_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, aDRoleAssignments_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ai.procyon.grpc.common.PolicyRule)) {
      return super.equals(obj);
    }
    com.ai.procyon.grpc.common.PolicyRule other = (com.ai.procyon.grpc.common.PolicyRule) obj;

    if (hasObjectRef() != other.hasObjectRef()) return false;
    if (hasObjectRef()) {
      if (!getObjectRef()
          .equals(other.getObjectRef())) return false;
    }
    if (!getPrincipal()
        .equals(other.getPrincipal())) return false;
    if (hasGcpRoleTarget() != other.hasGcpRoleTarget()) return false;
    if (hasGcpRoleTarget()) {
      if (!getGcpRoleTarget()
          .equals(other.getGcpRoleTarget())) return false;
    }
    if (hasServices() != other.hasServices()) return false;
    if (hasServices()) {
      if (!getServices()
          .equals(other.getServices())) return false;
    }
    if (getProcyonCreated()
        != other.getProcyonCreated()) return false;
    if (!getRoleAssignmentsList()
        .equals(other.getRoleAssignmentsList())) return false;
    if (!getADRoleAssignmentsList()
        .equals(other.getADRoleAssignmentsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasObjectRef()) {
      hash = (37 * hash) + OBJECTREF_FIELD_NUMBER;
      hash = (53 * hash) + getObjectRef().hashCode();
    }
    hash = (37 * hash) + PRINCIPAL_FIELD_NUMBER;
    hash = (53 * hash) + getPrincipal().hashCode();
    if (hasGcpRoleTarget()) {
      hash = (37 * hash) + GCPROLETARGET_FIELD_NUMBER;
      hash = (53 * hash) + getGcpRoleTarget().hashCode();
    }
    if (hasServices()) {
      hash = (37 * hash) + SERVICES_FIELD_NUMBER;
      hash = (53 * hash) + getServices().hashCode();
    }
    hash = (37 * hash) + PROCYONCREATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getProcyonCreated());
    if (getRoleAssignmentsCount() > 0) {
      hash = (37 * hash) + ROLEASSIGNMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getRoleAssignmentsList().hashCode();
    }
    if (getADRoleAssignmentsCount() > 0) {
      hash = (37 * hash) + ADROLEASSIGNMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getADRoleAssignmentsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ai.procyon.grpc.common.PolicyRule parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.PolicyRule parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.PolicyRule parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.PolicyRule parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.PolicyRule parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.PolicyRule parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.PolicyRule parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.PolicyRule parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.PolicyRule parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.PolicyRule parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.PolicyRule parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.PolicyRule parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ai.procyon.grpc.common.PolicyRule prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.PolicyRule}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.PolicyRule)
      com.ai.procyon.grpc.common.PolicyRuleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_PolicyRule_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_PolicyRule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ai.procyon.grpc.common.PolicyRule.class, com.ai.procyon.grpc.common.PolicyRule.Builder.class);
    }

    // Construct using com.ai.procyon.grpc.common.PolicyRule.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRoleAssignmentsFieldBuilder();
        getADRoleAssignmentsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (objectRefBuilder_ == null) {
        objectRef_ = null;
      } else {
        objectRef_ = null;
        objectRefBuilder_ = null;
      }
      principal_ = "";

      if (gcpRoleTargetBuilder_ == null) {
        gcpRoleTarget_ = null;
      } else {
        gcpRoleTarget_ = null;
        gcpRoleTargetBuilder_ = null;
      }
      if (servicesBuilder_ == null) {
        services_ = null;
      } else {
        services_ = null;
        servicesBuilder_ = null;
      }
      procyonCreated_ = false;

      if (roleAssignmentsBuilder_ == null) {
        roleAssignments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        roleAssignmentsBuilder_.clear();
      }
      if (aDRoleAssignmentsBuilder_ == null) {
        aDRoleAssignments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        aDRoleAssignmentsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_PolicyRule_descriptor;
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.PolicyRule getDefaultInstanceForType() {
      return com.ai.procyon.grpc.common.PolicyRule.getDefaultInstance();
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.PolicyRule build() {
      com.ai.procyon.grpc.common.PolicyRule result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.PolicyRule buildPartial() {
      com.ai.procyon.grpc.common.PolicyRule result = new com.ai.procyon.grpc.common.PolicyRule(this);
      int from_bitField0_ = bitField0_;
      if (objectRefBuilder_ == null) {
        result.objectRef_ = objectRef_;
      } else {
        result.objectRef_ = objectRefBuilder_.build();
      }
      result.principal_ = principal_;
      if (gcpRoleTargetBuilder_ == null) {
        result.gcpRoleTarget_ = gcpRoleTarget_;
      } else {
        result.gcpRoleTarget_ = gcpRoleTargetBuilder_.build();
      }
      if (servicesBuilder_ == null) {
        result.services_ = services_;
      } else {
        result.services_ = servicesBuilder_.build();
      }
      result.procyonCreated_ = procyonCreated_;
      if (roleAssignmentsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          roleAssignments_ = java.util.Collections.unmodifiableList(roleAssignments_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.roleAssignments_ = roleAssignments_;
      } else {
        result.roleAssignments_ = roleAssignmentsBuilder_.build();
      }
      if (aDRoleAssignmentsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          aDRoleAssignments_ = java.util.Collections.unmodifiableList(aDRoleAssignments_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.aDRoleAssignments_ = aDRoleAssignments_;
      } else {
        result.aDRoleAssignments_ = aDRoleAssignmentsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ai.procyon.grpc.common.PolicyRule) {
        return mergeFrom((com.ai.procyon.grpc.common.PolicyRule)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ai.procyon.grpc.common.PolicyRule other) {
      if (other == com.ai.procyon.grpc.common.PolicyRule.getDefaultInstance()) return this;
      if (other.hasObjectRef()) {
        mergeObjectRef(other.getObjectRef());
      }
      if (!other.getPrincipal().isEmpty()) {
        principal_ = other.principal_;
        onChanged();
      }
      if (other.hasGcpRoleTarget()) {
        mergeGcpRoleTarget(other.getGcpRoleTarget());
      }
      if (other.hasServices()) {
        mergeServices(other.getServices());
      }
      if (other.getProcyonCreated() != false) {
        setProcyonCreated(other.getProcyonCreated());
      }
      if (roleAssignmentsBuilder_ == null) {
        if (!other.roleAssignments_.isEmpty()) {
          if (roleAssignments_.isEmpty()) {
            roleAssignments_ = other.roleAssignments_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRoleAssignmentsIsMutable();
            roleAssignments_.addAll(other.roleAssignments_);
          }
          onChanged();
        }
      } else {
        if (!other.roleAssignments_.isEmpty()) {
          if (roleAssignmentsBuilder_.isEmpty()) {
            roleAssignmentsBuilder_.dispose();
            roleAssignmentsBuilder_ = null;
            roleAssignments_ = other.roleAssignments_;
            bitField0_ = (bitField0_ & ~0x00000001);
            roleAssignmentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRoleAssignmentsFieldBuilder() : null;
          } else {
            roleAssignmentsBuilder_.addAllMessages(other.roleAssignments_);
          }
        }
      }
      if (aDRoleAssignmentsBuilder_ == null) {
        if (!other.aDRoleAssignments_.isEmpty()) {
          if (aDRoleAssignments_.isEmpty()) {
            aDRoleAssignments_ = other.aDRoleAssignments_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureADRoleAssignmentsIsMutable();
            aDRoleAssignments_.addAll(other.aDRoleAssignments_);
          }
          onChanged();
        }
      } else {
        if (!other.aDRoleAssignments_.isEmpty()) {
          if (aDRoleAssignmentsBuilder_.isEmpty()) {
            aDRoleAssignmentsBuilder_.dispose();
            aDRoleAssignmentsBuilder_ = null;
            aDRoleAssignments_ = other.aDRoleAssignments_;
            bitField0_ = (bitField0_ & ~0x00000002);
            aDRoleAssignmentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getADRoleAssignmentsFieldBuilder() : null;
          } else {
            aDRoleAssignmentsBuilder_.addAllMessages(other.aDRoleAssignments_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ai.procyon.grpc.common.PolicyRule parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ai.procyon.grpc.common.PolicyRule) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.ai.procyon.grpc.common.ObjectRef objectRef_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ai.procyon.grpc.common.ObjectRef, com.ai.procyon.grpc.common.ObjectRef.Builder, com.ai.procyon.grpc.common.ObjectRefOrBuilder> objectRefBuilder_;
    /**
     * <code>.model.ObjectRef ObjectRef = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the objectRef field is set.
     */
    public boolean hasObjectRef() {
      return objectRefBuilder_ != null || objectRef_ != null;
    }
    /**
     * <code>.model.ObjectRef ObjectRef = 1 [(.gogoproto.nullable) = false];</code>
     * @return The objectRef.
     */
    public com.ai.procyon.grpc.common.ObjectRef getObjectRef() {
      if (objectRefBuilder_ == null) {
        return objectRef_ == null ? com.ai.procyon.grpc.common.ObjectRef.getDefaultInstance() : objectRef_;
      } else {
        return objectRefBuilder_.getMessage();
      }
    }
    /**
     * <code>.model.ObjectRef ObjectRef = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder setObjectRef(com.ai.procyon.grpc.common.ObjectRef value) {
      if (objectRefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        objectRef_ = value;
        onChanged();
      } else {
        objectRefBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.model.ObjectRef ObjectRef = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder setObjectRef(
        com.ai.procyon.grpc.common.ObjectRef.Builder builderForValue) {
      if (objectRefBuilder_ == null) {
        objectRef_ = builderForValue.build();
        onChanged();
      } else {
        objectRefBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.model.ObjectRef ObjectRef = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder mergeObjectRef(com.ai.procyon.grpc.common.ObjectRef value) {
      if (objectRefBuilder_ == null) {
        if (objectRef_ != null) {
          objectRef_ =
            com.ai.procyon.grpc.common.ObjectRef.newBuilder(objectRef_).mergeFrom(value).buildPartial();
        } else {
          objectRef_ = value;
        }
        onChanged();
      } else {
        objectRefBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.model.ObjectRef ObjectRef = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder clearObjectRef() {
      if (objectRefBuilder_ == null) {
        objectRef_ = null;
        onChanged();
      } else {
        objectRef_ = null;
        objectRefBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.model.ObjectRef ObjectRef = 1 [(.gogoproto.nullable) = false];</code>
     */
    public com.ai.procyon.grpc.common.ObjectRef.Builder getObjectRefBuilder() {
      
      onChanged();
      return getObjectRefFieldBuilder().getBuilder();
    }
    /**
     * <code>.model.ObjectRef ObjectRef = 1 [(.gogoproto.nullable) = false];</code>
     */
    public com.ai.procyon.grpc.common.ObjectRefOrBuilder getObjectRefOrBuilder() {
      if (objectRefBuilder_ != null) {
        return objectRefBuilder_.getMessageOrBuilder();
      } else {
        return objectRef_ == null ?
            com.ai.procyon.grpc.common.ObjectRef.getDefaultInstance() : objectRef_;
      }
    }
    /**
     * <code>.model.ObjectRef ObjectRef = 1 [(.gogoproto.nullable) = false];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ai.procyon.grpc.common.ObjectRef, com.ai.procyon.grpc.common.ObjectRef.Builder, com.ai.procyon.grpc.common.ObjectRefOrBuilder> 
        getObjectRefFieldBuilder() {
      if (objectRefBuilder_ == null) {
        objectRefBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ai.procyon.grpc.common.ObjectRef, com.ai.procyon.grpc.common.ObjectRef.Builder, com.ai.procyon.grpc.common.ObjectRefOrBuilder>(
                getObjectRef(),
                getParentForChildren(),
                isClean());
        objectRef_ = null;
      }
      return objectRefBuilder_;
    }

    private java.lang.Object principal_ = "";
    /**
     * <code>string Principal = 2;</code>
     * @return The principal.
     */
    public java.lang.String getPrincipal() {
      java.lang.Object ref = principal_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        principal_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Principal = 2;</code>
     * @return The bytes for principal.
     */
    public com.google.protobuf.ByteString
        getPrincipalBytes() {
      java.lang.Object ref = principal_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        principal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Principal = 2;</code>
     * @param value The principal to set.
     * @return This builder for chaining.
     */
    public Builder setPrincipal(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      principal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Principal = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrincipal() {
      
      principal_ = getDefaultInstance().getPrincipal();
      onChanged();
      return this;
    }
    /**
     * <code>string Principal = 2;</code>
     * @param value The bytes for principal to set.
     * @return This builder for chaining.
     */
    public Builder setPrincipalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      principal_ = value;
      onChanged();
      return this;
    }

    private com.ai.procyon.grpc.common.ObjectRef gcpRoleTarget_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ai.procyon.grpc.common.ObjectRef, com.ai.procyon.grpc.common.ObjectRef.Builder, com.ai.procyon.grpc.common.ObjectRefOrBuilder> gcpRoleTargetBuilder_;
    /**
     * <pre>
     * used only when 'ObjectRef' is a GCP role
     * </pre>
     *
     * <code>.model.ObjectRef GcpRoleTarget = 3;</code>
     * @return Whether the gcpRoleTarget field is set.
     */
    public boolean hasGcpRoleTarget() {
      return gcpRoleTargetBuilder_ != null || gcpRoleTarget_ != null;
    }
    /**
     * <pre>
     * used only when 'ObjectRef' is a GCP role
     * </pre>
     *
     * <code>.model.ObjectRef GcpRoleTarget = 3;</code>
     * @return The gcpRoleTarget.
     */
    public com.ai.procyon.grpc.common.ObjectRef getGcpRoleTarget() {
      if (gcpRoleTargetBuilder_ == null) {
        return gcpRoleTarget_ == null ? com.ai.procyon.grpc.common.ObjectRef.getDefaultInstance() : gcpRoleTarget_;
      } else {
        return gcpRoleTargetBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * used only when 'ObjectRef' is a GCP role
     * </pre>
     *
     * <code>.model.ObjectRef GcpRoleTarget = 3;</code>
     */
    public Builder setGcpRoleTarget(com.ai.procyon.grpc.common.ObjectRef value) {
      if (gcpRoleTargetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gcpRoleTarget_ = value;
        onChanged();
      } else {
        gcpRoleTargetBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * used only when 'ObjectRef' is a GCP role
     * </pre>
     *
     * <code>.model.ObjectRef GcpRoleTarget = 3;</code>
     */
    public Builder setGcpRoleTarget(
        com.ai.procyon.grpc.common.ObjectRef.Builder builderForValue) {
      if (gcpRoleTargetBuilder_ == null) {
        gcpRoleTarget_ = builderForValue.build();
        onChanged();
      } else {
        gcpRoleTargetBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * used only when 'ObjectRef' is a GCP role
     * </pre>
     *
     * <code>.model.ObjectRef GcpRoleTarget = 3;</code>
     */
    public Builder mergeGcpRoleTarget(com.ai.procyon.grpc.common.ObjectRef value) {
      if (gcpRoleTargetBuilder_ == null) {
        if (gcpRoleTarget_ != null) {
          gcpRoleTarget_ =
            com.ai.procyon.grpc.common.ObjectRef.newBuilder(gcpRoleTarget_).mergeFrom(value).buildPartial();
        } else {
          gcpRoleTarget_ = value;
        }
        onChanged();
      } else {
        gcpRoleTargetBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * used only when 'ObjectRef' is a GCP role
     * </pre>
     *
     * <code>.model.ObjectRef GcpRoleTarget = 3;</code>
     */
    public Builder clearGcpRoleTarget() {
      if (gcpRoleTargetBuilder_ == null) {
        gcpRoleTarget_ = null;
        onChanged();
      } else {
        gcpRoleTarget_ = null;
        gcpRoleTargetBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * used only when 'ObjectRef' is a GCP role
     * </pre>
     *
     * <code>.model.ObjectRef GcpRoleTarget = 3;</code>
     */
    public com.ai.procyon.grpc.common.ObjectRef.Builder getGcpRoleTargetBuilder() {
      
      onChanged();
      return getGcpRoleTargetFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * used only when 'ObjectRef' is a GCP role
     * </pre>
     *
     * <code>.model.ObjectRef GcpRoleTarget = 3;</code>
     */
    public com.ai.procyon.grpc.common.ObjectRefOrBuilder getGcpRoleTargetOrBuilder() {
      if (gcpRoleTargetBuilder_ != null) {
        return gcpRoleTargetBuilder_.getMessageOrBuilder();
      } else {
        return gcpRoleTarget_ == null ?
            com.ai.procyon.grpc.common.ObjectRef.getDefaultInstance() : gcpRoleTarget_;
      }
    }
    /**
     * <pre>
     * used only when 'ObjectRef' is a GCP role
     * </pre>
     *
     * <code>.model.ObjectRef GcpRoleTarget = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ai.procyon.grpc.common.ObjectRef, com.ai.procyon.grpc.common.ObjectRef.Builder, com.ai.procyon.grpc.common.ObjectRefOrBuilder> 
        getGcpRoleTargetFieldBuilder() {
      if (gcpRoleTargetBuilder_ == null) {
        gcpRoleTargetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ai.procyon.grpc.common.ObjectRef, com.ai.procyon.grpc.common.ObjectRef.Builder, com.ai.procyon.grpc.common.ObjectRefOrBuilder>(
                getGcpRoleTarget(),
                getParentForChildren(),
                isClean());
        gcpRoleTarget_ = null;
      }
      return gcpRoleTargetBuilder_;
    }

    private com.ai.procyon.grpc.common.References services_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ai.procyon.grpc.common.References, com.ai.procyon.grpc.common.References.Builder, com.ai.procyon.grpc.common.ReferencesOrBuilder> servicesBuilder_;
    /**
     * <code>.model.References Services = 4 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     * @return Whether the services field is set.
     */
    public boolean hasServices() {
      return servicesBuilder_ != null || services_ != null;
    }
    /**
     * <code>.model.References Services = 4 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     * @return The services.
     */
    public com.ai.procyon.grpc.common.References getServices() {
      if (servicesBuilder_ == null) {
        return services_ == null ? com.ai.procyon.grpc.common.References.getDefaultInstance() : services_;
      } else {
        return servicesBuilder_.getMessage();
      }
    }
    /**
     * <code>.model.References Services = 4 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     */
    public Builder setServices(com.ai.procyon.grpc.common.References value) {
      if (servicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        services_ = value;
        onChanged();
      } else {
        servicesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.model.References Services = 4 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     */
    public Builder setServices(
        com.ai.procyon.grpc.common.References.Builder builderForValue) {
      if (servicesBuilder_ == null) {
        services_ = builderForValue.build();
        onChanged();
      } else {
        servicesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.model.References Services = 4 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     */
    public Builder mergeServices(com.ai.procyon.grpc.common.References value) {
      if (servicesBuilder_ == null) {
        if (services_ != null) {
          services_ =
            com.ai.procyon.grpc.common.References.newBuilder(services_).mergeFrom(value).buildPartial();
        } else {
          services_ = value;
        }
        onChanged();
      } else {
        servicesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.model.References Services = 4 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     */
    public Builder clearServices() {
      if (servicesBuilder_ == null) {
        services_ = null;
        onChanged();
      } else {
        services_ = null;
        servicesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.model.References Services = 4 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     */
    public com.ai.procyon.grpc.common.References.Builder getServicesBuilder() {
      
      onChanged();
      return getServicesFieldBuilder().getBuilder();
    }
    /**
     * <code>.model.References Services = 4 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     */
    public com.ai.procyon.grpc.common.ReferencesOrBuilder getServicesOrBuilder() {
      if (servicesBuilder_ != null) {
        return servicesBuilder_.getMessageOrBuilder();
      } else {
        return services_ == null ?
            com.ai.procyon.grpc.common.References.getDefaultInstance() : services_;
      }
    }
    /**
     * <code>.model.References Services = 4 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"type:text&#92;""];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ai.procyon.grpc.common.References, com.ai.procyon.grpc.common.References.Builder, com.ai.procyon.grpc.common.ReferencesOrBuilder> 
        getServicesFieldBuilder() {
      if (servicesBuilder_ == null) {
        servicesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ai.procyon.grpc.common.References, com.ai.procyon.grpc.common.References.Builder, com.ai.procyon.grpc.common.ReferencesOrBuilder>(
                getServices(),
                getParentForChildren(),
                isClean());
        services_ = null;
      }
      return servicesBuilder_;
    }

    private boolean procyonCreated_ ;
    /**
     * <code>bool ProcyonCreated = 5;</code>
     * @return The procyonCreated.
     */
    @java.lang.Override
    public boolean getProcyonCreated() {
      return procyonCreated_;
    }
    /**
     * <code>bool ProcyonCreated = 5;</code>
     * @param value The procyonCreated to set.
     * @return This builder for chaining.
     */
    public Builder setProcyonCreated(boolean value) {
      
      procyonCreated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool ProcyonCreated = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcyonCreated() {
      
      procyonCreated_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.ai.procyon.grpc.common.RoleAssignment> roleAssignments_ =
      java.util.Collections.emptyList();
    private void ensureRoleAssignmentsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        roleAssignments_ = new java.util.ArrayList<com.ai.procyon.grpc.common.RoleAssignment>(roleAssignments_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ai.procyon.grpc.common.RoleAssignment, com.ai.procyon.grpc.common.RoleAssignment.Builder, com.ai.procyon.grpc.common.RoleAssignmentOrBuilder> roleAssignmentsBuilder_;

    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public java.util.List<com.ai.procyon.grpc.common.RoleAssignment> getRoleAssignmentsList() {
      if (roleAssignmentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(roleAssignments_);
      } else {
        return roleAssignmentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public int getRoleAssignmentsCount() {
      if (roleAssignmentsBuilder_ == null) {
        return roleAssignments_.size();
      } else {
        return roleAssignmentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public com.ai.procyon.grpc.common.RoleAssignment getRoleAssignments(int index) {
      if (roleAssignmentsBuilder_ == null) {
        return roleAssignments_.get(index);
      } else {
        return roleAssignmentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public Builder setRoleAssignments(
        int index, com.ai.procyon.grpc.common.RoleAssignment value) {
      if (roleAssignmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoleAssignmentsIsMutable();
        roleAssignments_.set(index, value);
        onChanged();
      } else {
        roleAssignmentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public Builder setRoleAssignments(
        int index, com.ai.procyon.grpc.common.RoleAssignment.Builder builderForValue) {
      if (roleAssignmentsBuilder_ == null) {
        ensureRoleAssignmentsIsMutable();
        roleAssignments_.set(index, builderForValue.build());
        onChanged();
      } else {
        roleAssignmentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public Builder addRoleAssignments(com.ai.procyon.grpc.common.RoleAssignment value) {
      if (roleAssignmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoleAssignmentsIsMutable();
        roleAssignments_.add(value);
        onChanged();
      } else {
        roleAssignmentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public Builder addRoleAssignments(
        int index, com.ai.procyon.grpc.common.RoleAssignment value) {
      if (roleAssignmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoleAssignmentsIsMutable();
        roleAssignments_.add(index, value);
        onChanged();
      } else {
        roleAssignmentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public Builder addRoleAssignments(
        com.ai.procyon.grpc.common.RoleAssignment.Builder builderForValue) {
      if (roleAssignmentsBuilder_ == null) {
        ensureRoleAssignmentsIsMutable();
        roleAssignments_.add(builderForValue.build());
        onChanged();
      } else {
        roleAssignmentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public Builder addRoleAssignments(
        int index, com.ai.procyon.grpc.common.RoleAssignment.Builder builderForValue) {
      if (roleAssignmentsBuilder_ == null) {
        ensureRoleAssignmentsIsMutable();
        roleAssignments_.add(index, builderForValue.build());
        onChanged();
      } else {
        roleAssignmentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public Builder addAllRoleAssignments(
        java.lang.Iterable<? extends com.ai.procyon.grpc.common.RoleAssignment> values) {
      if (roleAssignmentsBuilder_ == null) {
        ensureRoleAssignmentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, roleAssignments_);
        onChanged();
      } else {
        roleAssignmentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public Builder clearRoleAssignments() {
      if (roleAssignmentsBuilder_ == null) {
        roleAssignments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        roleAssignmentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public Builder removeRoleAssignments(int index) {
      if (roleAssignmentsBuilder_ == null) {
        ensureRoleAssignmentsIsMutable();
        roleAssignments_.remove(index);
        onChanged();
      } else {
        roleAssignmentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public com.ai.procyon.grpc.common.RoleAssignment.Builder getRoleAssignmentsBuilder(
        int index) {
      return getRoleAssignmentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public com.ai.procyon.grpc.common.RoleAssignmentOrBuilder getRoleAssignmentsOrBuilder(
        int index) {
      if (roleAssignmentsBuilder_ == null) {
        return roleAssignments_.get(index);  } else {
        return roleAssignmentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public java.util.List<? extends com.ai.procyon.grpc.common.RoleAssignmentOrBuilder> 
         getRoleAssignmentsOrBuilderList() {
      if (roleAssignmentsBuilder_ != null) {
        return roleAssignmentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(roleAssignments_);
      }
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public com.ai.procyon.grpc.common.RoleAssignment.Builder addRoleAssignmentsBuilder() {
      return getRoleAssignmentsFieldBuilder().addBuilder(
          com.ai.procyon.grpc.common.RoleAssignment.getDefaultInstance());
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public com.ai.procyon.grpc.common.RoleAssignment.Builder addRoleAssignmentsBuilder(
        int index) {
      return getRoleAssignmentsFieldBuilder().addBuilder(
          index, com.ai.procyon.grpc.common.RoleAssignment.getDefaultInstance());
    }
    /**
     * <code>repeated .model.RoleAssignment RoleAssignments = 6;</code>
     */
    public java.util.List<com.ai.procyon.grpc.common.RoleAssignment.Builder> 
         getRoleAssignmentsBuilderList() {
      return getRoleAssignmentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ai.procyon.grpc.common.RoleAssignment, com.ai.procyon.grpc.common.RoleAssignment.Builder, com.ai.procyon.grpc.common.RoleAssignmentOrBuilder> 
        getRoleAssignmentsFieldBuilder() {
      if (roleAssignmentsBuilder_ == null) {
        roleAssignmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ai.procyon.grpc.common.RoleAssignment, com.ai.procyon.grpc.common.RoleAssignment.Builder, com.ai.procyon.grpc.common.RoleAssignmentOrBuilder>(
                roleAssignments_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        roleAssignments_ = null;
      }
      return roleAssignmentsBuilder_;
    }

    private java.util.List<com.ai.procyon.grpc.common.RoleAssignment> aDRoleAssignments_ =
      java.util.Collections.emptyList();
    private void ensureADRoleAssignmentsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        aDRoleAssignments_ = new java.util.ArrayList<com.ai.procyon.grpc.common.RoleAssignment>(aDRoleAssignments_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ai.procyon.grpc.common.RoleAssignment, com.ai.procyon.grpc.common.RoleAssignment.Builder, com.ai.procyon.grpc.common.RoleAssignmentOrBuilder> aDRoleAssignmentsBuilder_;

    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public java.util.List<com.ai.procyon.grpc.common.RoleAssignment> getADRoleAssignmentsList() {
      if (aDRoleAssignmentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(aDRoleAssignments_);
      } else {
        return aDRoleAssignmentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public int getADRoleAssignmentsCount() {
      if (aDRoleAssignmentsBuilder_ == null) {
        return aDRoleAssignments_.size();
      } else {
        return aDRoleAssignmentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public com.ai.procyon.grpc.common.RoleAssignment getADRoleAssignments(int index) {
      if (aDRoleAssignmentsBuilder_ == null) {
        return aDRoleAssignments_.get(index);
      } else {
        return aDRoleAssignmentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public Builder setADRoleAssignments(
        int index, com.ai.procyon.grpc.common.RoleAssignment value) {
      if (aDRoleAssignmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureADRoleAssignmentsIsMutable();
        aDRoleAssignments_.set(index, value);
        onChanged();
      } else {
        aDRoleAssignmentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public Builder setADRoleAssignments(
        int index, com.ai.procyon.grpc.common.RoleAssignment.Builder builderForValue) {
      if (aDRoleAssignmentsBuilder_ == null) {
        ensureADRoleAssignmentsIsMutable();
        aDRoleAssignments_.set(index, builderForValue.build());
        onChanged();
      } else {
        aDRoleAssignmentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public Builder addADRoleAssignments(com.ai.procyon.grpc.common.RoleAssignment value) {
      if (aDRoleAssignmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureADRoleAssignmentsIsMutable();
        aDRoleAssignments_.add(value);
        onChanged();
      } else {
        aDRoleAssignmentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public Builder addADRoleAssignments(
        int index, com.ai.procyon.grpc.common.RoleAssignment value) {
      if (aDRoleAssignmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureADRoleAssignmentsIsMutable();
        aDRoleAssignments_.add(index, value);
        onChanged();
      } else {
        aDRoleAssignmentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public Builder addADRoleAssignments(
        com.ai.procyon.grpc.common.RoleAssignment.Builder builderForValue) {
      if (aDRoleAssignmentsBuilder_ == null) {
        ensureADRoleAssignmentsIsMutable();
        aDRoleAssignments_.add(builderForValue.build());
        onChanged();
      } else {
        aDRoleAssignmentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public Builder addADRoleAssignments(
        int index, com.ai.procyon.grpc.common.RoleAssignment.Builder builderForValue) {
      if (aDRoleAssignmentsBuilder_ == null) {
        ensureADRoleAssignmentsIsMutable();
        aDRoleAssignments_.add(index, builderForValue.build());
        onChanged();
      } else {
        aDRoleAssignmentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public Builder addAllADRoleAssignments(
        java.lang.Iterable<? extends com.ai.procyon.grpc.common.RoleAssignment> values) {
      if (aDRoleAssignmentsBuilder_ == null) {
        ensureADRoleAssignmentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, aDRoleAssignments_);
        onChanged();
      } else {
        aDRoleAssignmentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public Builder clearADRoleAssignments() {
      if (aDRoleAssignmentsBuilder_ == null) {
        aDRoleAssignments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        aDRoleAssignmentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public Builder removeADRoleAssignments(int index) {
      if (aDRoleAssignmentsBuilder_ == null) {
        ensureADRoleAssignmentsIsMutable();
        aDRoleAssignments_.remove(index);
        onChanged();
      } else {
        aDRoleAssignmentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public com.ai.procyon.grpc.common.RoleAssignment.Builder getADRoleAssignmentsBuilder(
        int index) {
      return getADRoleAssignmentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public com.ai.procyon.grpc.common.RoleAssignmentOrBuilder getADRoleAssignmentsOrBuilder(
        int index) {
      if (aDRoleAssignmentsBuilder_ == null) {
        return aDRoleAssignments_.get(index);  } else {
        return aDRoleAssignmentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public java.util.List<? extends com.ai.procyon.grpc.common.RoleAssignmentOrBuilder> 
         getADRoleAssignmentsOrBuilderList() {
      if (aDRoleAssignmentsBuilder_ != null) {
        return aDRoleAssignmentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(aDRoleAssignments_);
      }
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public com.ai.procyon.grpc.common.RoleAssignment.Builder addADRoleAssignmentsBuilder() {
      return getADRoleAssignmentsFieldBuilder().addBuilder(
          com.ai.procyon.grpc.common.RoleAssignment.getDefaultInstance());
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public com.ai.procyon.grpc.common.RoleAssignment.Builder addADRoleAssignmentsBuilder(
        int index) {
      return getADRoleAssignmentsFieldBuilder().addBuilder(
          index, com.ai.procyon.grpc.common.RoleAssignment.getDefaultInstance());
    }
    /**
     * <code>repeated .model.RoleAssignment ADRoleAssignments = 7;</code>
     */
    public java.util.List<com.ai.procyon.grpc.common.RoleAssignment.Builder> 
         getADRoleAssignmentsBuilderList() {
      return getADRoleAssignmentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ai.procyon.grpc.common.RoleAssignment, com.ai.procyon.grpc.common.RoleAssignment.Builder, com.ai.procyon.grpc.common.RoleAssignmentOrBuilder> 
        getADRoleAssignmentsFieldBuilder() {
      if (aDRoleAssignmentsBuilder_ == null) {
        aDRoleAssignmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ai.procyon.grpc.common.RoleAssignment, com.ai.procyon.grpc.common.RoleAssignment.Builder, com.ai.procyon.grpc.common.RoleAssignmentOrBuilder>(
                aDRoleAssignments_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        aDRoleAssignments_ = null;
      }
      return aDRoleAssignmentsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.PolicyRule)
  }

  // @@protoc_insertion_point(class_scope:model.PolicyRule)
  private static final com.ai.procyon.grpc.common.PolicyRule DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ai.procyon.grpc.common.PolicyRule();
  }

  public static com.ai.procyon.grpc.common.PolicyRule getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PolicyRule>
      PARSER = new com.google.protobuf.AbstractParser<PolicyRule>() {
    @java.lang.Override
    public PolicyRule parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PolicyRule(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PolicyRule> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PolicyRule> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ai.procyon.grpc.common.PolicyRule getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

