// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

public interface PolicyRuleSpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.PolicyRuleSpec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Description = 1;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string Description = 1;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>map&lt;string, .model.PolicyRules&gt; ActionMap = 2;</code>
   */
  int getActionMapCount();
  /**
   * <code>map&lt;string, .model.PolicyRules&gt; ActionMap = 2;</code>
   */
  boolean containsActionMap(
      java.lang.String key);
  /**
   * Use {@link #getActionMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.ai.procyon.grpc.common.PolicyRules>
  getActionMap();
  /**
   * <code>map&lt;string, .model.PolicyRules&gt; ActionMap = 2;</code>
   */
  java.util.Map<java.lang.String, com.ai.procyon.grpc.common.PolicyRules>
  getActionMapMap();
  /**
   * <code>map&lt;string, .model.PolicyRules&gt; ActionMap = 2;</code>
   */

  com.ai.procyon.grpc.common.PolicyRules getActionMapOrDefault(
      java.lang.String key,
      com.ai.procyon.grpc.common.PolicyRules defaultValue);
  /**
   * <code>map&lt;string, .model.PolicyRules&gt; ActionMap = 2;</code>
   */

  com.ai.procyon.grpc.common.PolicyRules getActionMapOrThrow(
      java.lang.String key);
}
