// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common.proto

package com.ai.procyon.grpc.common;

/**
* Validates {@code Resource} protobuf objects.
*/
public class ResourceValidator implements io.envoyproxy.pgv.ValidatorImpl<com.ai.procyon.grpc.common.Resource>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(com.ai.procyon.grpc.common.Resource.class)) return new ResourceValidator();
		
		return null;
	}
		
	
		
	
		
	
		
	
		
	
		
	
		
	
		
	
		
	
	

	public void assertValid(com.ai.procyon.grpc.common.Resource proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			// Validate Target
			if (proto.hasTarget()) index.validatorFor(proto.getTarget()).assertValid(proto.getTarget());
	// no validation rules for Action

	// no validation rules for Principal

	// no validation rules for Justification

	
			// Validate Approvers
			if (proto.hasApprovers()) index.validatorFor(proto.getApprovers()).assertValid(proto.getApprovers());
	// no validation rules for Approved

	// no validation rules for ApproverComments

	
			// Validate GcpRoleTarget
			if (proto.hasGcpRoleTarget()) index.validatorFor(proto.getGcpRoleTarget()).assertValid(proto.getGcpRoleTarget());
	
			// Validate Services
			if (proto.hasServices()) index.validatorFor(proto.getServices()).assertValid(proto.getServices());
	
	}

}

