// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common.proto

package com.ai.procyon.grpc.common;

/**
* Validates {@code RuleList} protobuf objects.
*/
public class RuleListValidator implements io.envoyproxy.pgv.ValidatorImpl<com.ai.procyon.grpc.common.RuleList>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(com.ai.procyon.grpc.common.RuleList.class)) return new RuleListValidator();
		
		return null;
	}
		
	
	

	public void assertValid(com.ai.procyon.grpc.common.RuleList proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			io.envoyproxy.pgv.RepeatedValidation.forEach(proto.getRulesList(), item -> {
				
			// Validate Rules
			if (true) index.validatorFor(item).assertValid(item);
			});

	
	}

}

