// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

public interface SecureStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.SecureString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string SecureData = 1;</code>
   * @return The secureData.
   */
  java.lang.String getSecureData();
  /**
   * <code>string SecureData = 1;</code>
   * @return The bytes for secureData.
   */
  com.google.protobuf.ByteString
      getSecureDataBytes();
}
