// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common.proto

package com.ai.procyon.grpc.common;

/**
* Validates {@code SecureString} protobuf objects.
*/
public class SecureStringValidator implements io.envoyproxy.pgv.ValidatorImpl<com.ai.procyon.grpc.common.SecureString>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(com.ai.procyon.grpc.common.SecureString.class)) return new SecureStringValidator();
		
		return null;
	}
		
	
	

	public void assertValid(com.ai.procyon.grpc.common.SecureString proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for SecureData

	
	}

}

