// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

/**
 * Protobuf type {@code model.ServiceProviderAttributeValueList}
 */
public final class ServiceProviderAttributeValueList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.ServiceProviderAttributeValueList)
    ServiceProviderAttributeValueListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServiceProviderAttributeValueList.newBuilder() to construct.
  private ServiceProviderAttributeValueList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServiceProviderAttributeValueList() {
    serviceProviderAttributeValues_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServiceProviderAttributeValueList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServiceProviderAttributeValueList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              serviceProviderAttributeValues_ = new java.util.ArrayList<com.ai.procyon.grpc.common.ServiceProviderAttributeValue>();
              mutable_bitField0_ |= 0x00000001;
            }
            serviceProviderAttributeValues_.add(
                input.readMessage(com.ai.procyon.grpc.common.ServiceProviderAttributeValue.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        serviceProviderAttributeValues_ = java.util.Collections.unmodifiableList(serviceProviderAttributeValues_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ai.procyon.grpc.common.CommonProto.internal_static_model_ServiceProviderAttributeValueList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ai.procyon.grpc.common.CommonProto.internal_static_model_ServiceProviderAttributeValueList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ai.procyon.grpc.common.ServiceProviderAttributeValueList.class, com.ai.procyon.grpc.common.ServiceProviderAttributeValueList.Builder.class);
  }

  public static final int SERVICEPROVIDERATTRIBUTEVALUES_FIELD_NUMBER = 1;
  private java.util.List<com.ai.procyon.grpc.common.ServiceProviderAttributeValue> serviceProviderAttributeValues_;
  /**
   * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public java.util.List<com.ai.procyon.grpc.common.ServiceProviderAttributeValue> getServiceProviderAttributeValuesList() {
    return serviceProviderAttributeValues_;
  }
  /**
   * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ai.procyon.grpc.common.ServiceProviderAttributeValueOrBuilder> 
      getServiceProviderAttributeValuesOrBuilderList() {
    return serviceProviderAttributeValues_;
  }
  /**
   * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public int getServiceProviderAttributeValuesCount() {
    return serviceProviderAttributeValues_.size();
  }
  /**
   * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.ServiceProviderAttributeValue getServiceProviderAttributeValues(int index) {
    return serviceProviderAttributeValues_.get(index);
  }
  /**
   * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public com.ai.procyon.grpc.common.ServiceProviderAttributeValueOrBuilder getServiceProviderAttributeValuesOrBuilder(
      int index) {
    return serviceProviderAttributeValues_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < serviceProviderAttributeValues_.size(); i++) {
      output.writeMessage(1, serviceProviderAttributeValues_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < serviceProviderAttributeValues_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, serviceProviderAttributeValues_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ai.procyon.grpc.common.ServiceProviderAttributeValueList)) {
      return super.equals(obj);
    }
    com.ai.procyon.grpc.common.ServiceProviderAttributeValueList other = (com.ai.procyon.grpc.common.ServiceProviderAttributeValueList) obj;

    if (!getServiceProviderAttributeValuesList()
        .equals(other.getServiceProviderAttributeValuesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getServiceProviderAttributeValuesCount() > 0) {
      hash = (37 * hash) + SERVICEPROVIDERATTRIBUTEVALUES_FIELD_NUMBER;
      hash = (53 * hash) + getServiceProviderAttributeValuesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ai.procyon.grpc.common.ServiceProviderAttributeValueList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.ServiceProviderAttributeValueList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.ServiceProviderAttributeValueList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.ServiceProviderAttributeValueList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.ServiceProviderAttributeValueList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.ServiceProviderAttributeValueList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.ServiceProviderAttributeValueList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.ServiceProviderAttributeValueList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.ServiceProviderAttributeValueList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.ServiceProviderAttributeValueList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.ServiceProviderAttributeValueList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.ServiceProviderAttributeValueList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ai.procyon.grpc.common.ServiceProviderAttributeValueList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.ServiceProviderAttributeValueList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.ServiceProviderAttributeValueList)
      com.ai.procyon.grpc.common.ServiceProviderAttributeValueListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_ServiceProviderAttributeValueList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_ServiceProviderAttributeValueList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ai.procyon.grpc.common.ServiceProviderAttributeValueList.class, com.ai.procyon.grpc.common.ServiceProviderAttributeValueList.Builder.class);
    }

    // Construct using com.ai.procyon.grpc.common.ServiceProviderAttributeValueList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getServiceProviderAttributeValuesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (serviceProviderAttributeValuesBuilder_ == null) {
        serviceProviderAttributeValues_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        serviceProviderAttributeValuesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_ServiceProviderAttributeValueList_descriptor;
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.ServiceProviderAttributeValueList getDefaultInstanceForType() {
      return com.ai.procyon.grpc.common.ServiceProviderAttributeValueList.getDefaultInstance();
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.ServiceProviderAttributeValueList build() {
      com.ai.procyon.grpc.common.ServiceProviderAttributeValueList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.ServiceProviderAttributeValueList buildPartial() {
      com.ai.procyon.grpc.common.ServiceProviderAttributeValueList result = new com.ai.procyon.grpc.common.ServiceProviderAttributeValueList(this);
      int from_bitField0_ = bitField0_;
      if (serviceProviderAttributeValuesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          serviceProviderAttributeValues_ = java.util.Collections.unmodifiableList(serviceProviderAttributeValues_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.serviceProviderAttributeValues_ = serviceProviderAttributeValues_;
      } else {
        result.serviceProviderAttributeValues_ = serviceProviderAttributeValuesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ai.procyon.grpc.common.ServiceProviderAttributeValueList) {
        return mergeFrom((com.ai.procyon.grpc.common.ServiceProviderAttributeValueList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ai.procyon.grpc.common.ServiceProviderAttributeValueList other) {
      if (other == com.ai.procyon.grpc.common.ServiceProviderAttributeValueList.getDefaultInstance()) return this;
      if (serviceProviderAttributeValuesBuilder_ == null) {
        if (!other.serviceProviderAttributeValues_.isEmpty()) {
          if (serviceProviderAttributeValues_.isEmpty()) {
            serviceProviderAttributeValues_ = other.serviceProviderAttributeValues_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServiceProviderAttributeValuesIsMutable();
            serviceProviderAttributeValues_.addAll(other.serviceProviderAttributeValues_);
          }
          onChanged();
        }
      } else {
        if (!other.serviceProviderAttributeValues_.isEmpty()) {
          if (serviceProviderAttributeValuesBuilder_.isEmpty()) {
            serviceProviderAttributeValuesBuilder_.dispose();
            serviceProviderAttributeValuesBuilder_ = null;
            serviceProviderAttributeValues_ = other.serviceProviderAttributeValues_;
            bitField0_ = (bitField0_ & ~0x00000001);
            serviceProviderAttributeValuesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getServiceProviderAttributeValuesFieldBuilder() : null;
          } else {
            serviceProviderAttributeValuesBuilder_.addAllMessages(other.serviceProviderAttributeValues_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ai.procyon.grpc.common.ServiceProviderAttributeValueList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ai.procyon.grpc.common.ServiceProviderAttributeValueList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ai.procyon.grpc.common.ServiceProviderAttributeValue> serviceProviderAttributeValues_ =
      java.util.Collections.emptyList();
    private void ensureServiceProviderAttributeValuesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        serviceProviderAttributeValues_ = new java.util.ArrayList<com.ai.procyon.grpc.common.ServiceProviderAttributeValue>(serviceProviderAttributeValues_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ai.procyon.grpc.common.ServiceProviderAttributeValue, com.ai.procyon.grpc.common.ServiceProviderAttributeValue.Builder, com.ai.procyon.grpc.common.ServiceProviderAttributeValueOrBuilder> serviceProviderAttributeValuesBuilder_;

    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public java.util.List<com.ai.procyon.grpc.common.ServiceProviderAttributeValue> getServiceProviderAttributeValuesList() {
      if (serviceProviderAttributeValuesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(serviceProviderAttributeValues_);
      } else {
        return serviceProviderAttributeValuesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public int getServiceProviderAttributeValuesCount() {
      if (serviceProviderAttributeValuesBuilder_ == null) {
        return serviceProviderAttributeValues_.size();
      } else {
        return serviceProviderAttributeValuesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public com.ai.procyon.grpc.common.ServiceProviderAttributeValue getServiceProviderAttributeValues(int index) {
      if (serviceProviderAttributeValuesBuilder_ == null) {
        return serviceProviderAttributeValues_.get(index);
      } else {
        return serviceProviderAttributeValuesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder setServiceProviderAttributeValues(
        int index, com.ai.procyon.grpc.common.ServiceProviderAttributeValue value) {
      if (serviceProviderAttributeValuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceProviderAttributeValuesIsMutable();
        serviceProviderAttributeValues_.set(index, value);
        onChanged();
      } else {
        serviceProviderAttributeValuesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder setServiceProviderAttributeValues(
        int index, com.ai.procyon.grpc.common.ServiceProviderAttributeValue.Builder builderForValue) {
      if (serviceProviderAttributeValuesBuilder_ == null) {
        ensureServiceProviderAttributeValuesIsMutable();
        serviceProviderAttributeValues_.set(index, builderForValue.build());
        onChanged();
      } else {
        serviceProviderAttributeValuesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder addServiceProviderAttributeValues(com.ai.procyon.grpc.common.ServiceProviderAttributeValue value) {
      if (serviceProviderAttributeValuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceProviderAttributeValuesIsMutable();
        serviceProviderAttributeValues_.add(value);
        onChanged();
      } else {
        serviceProviderAttributeValuesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder addServiceProviderAttributeValues(
        int index, com.ai.procyon.grpc.common.ServiceProviderAttributeValue value) {
      if (serviceProviderAttributeValuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceProviderAttributeValuesIsMutable();
        serviceProviderAttributeValues_.add(index, value);
        onChanged();
      } else {
        serviceProviderAttributeValuesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder addServiceProviderAttributeValues(
        com.ai.procyon.grpc.common.ServiceProviderAttributeValue.Builder builderForValue) {
      if (serviceProviderAttributeValuesBuilder_ == null) {
        ensureServiceProviderAttributeValuesIsMutable();
        serviceProviderAttributeValues_.add(builderForValue.build());
        onChanged();
      } else {
        serviceProviderAttributeValuesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder addServiceProviderAttributeValues(
        int index, com.ai.procyon.grpc.common.ServiceProviderAttributeValue.Builder builderForValue) {
      if (serviceProviderAttributeValuesBuilder_ == null) {
        ensureServiceProviderAttributeValuesIsMutable();
        serviceProviderAttributeValues_.add(index, builderForValue.build());
        onChanged();
      } else {
        serviceProviderAttributeValuesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder addAllServiceProviderAttributeValues(
        java.lang.Iterable<? extends com.ai.procyon.grpc.common.ServiceProviderAttributeValue> values) {
      if (serviceProviderAttributeValuesBuilder_ == null) {
        ensureServiceProviderAttributeValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, serviceProviderAttributeValues_);
        onChanged();
      } else {
        serviceProviderAttributeValuesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder clearServiceProviderAttributeValues() {
      if (serviceProviderAttributeValuesBuilder_ == null) {
        serviceProviderAttributeValues_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        serviceProviderAttributeValuesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public Builder removeServiceProviderAttributeValues(int index) {
      if (serviceProviderAttributeValuesBuilder_ == null) {
        ensureServiceProviderAttributeValuesIsMutable();
        serviceProviderAttributeValues_.remove(index);
        onChanged();
      } else {
        serviceProviderAttributeValuesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public com.ai.procyon.grpc.common.ServiceProviderAttributeValue.Builder getServiceProviderAttributeValuesBuilder(
        int index) {
      return getServiceProviderAttributeValuesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public com.ai.procyon.grpc.common.ServiceProviderAttributeValueOrBuilder getServiceProviderAttributeValuesOrBuilder(
        int index) {
      if (serviceProviderAttributeValuesBuilder_ == null) {
        return serviceProviderAttributeValues_.get(index);  } else {
        return serviceProviderAttributeValuesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public java.util.List<? extends com.ai.procyon.grpc.common.ServiceProviderAttributeValueOrBuilder> 
         getServiceProviderAttributeValuesOrBuilderList() {
      if (serviceProviderAttributeValuesBuilder_ != null) {
        return serviceProviderAttributeValuesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(serviceProviderAttributeValues_);
      }
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public com.ai.procyon.grpc.common.ServiceProviderAttributeValue.Builder addServiceProviderAttributeValuesBuilder() {
      return getServiceProviderAttributeValuesFieldBuilder().addBuilder(
          com.ai.procyon.grpc.common.ServiceProviderAttributeValue.getDefaultInstance());
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public com.ai.procyon.grpc.common.ServiceProviderAttributeValue.Builder addServiceProviderAttributeValuesBuilder(
        int index) {
      return getServiceProviderAttributeValuesFieldBuilder().addBuilder(
          index, com.ai.procyon.grpc.common.ServiceProviderAttributeValue.getDefaultInstance());
    }
    /**
     * <code>repeated .model.ServiceProviderAttributeValue ServiceProviderAttributeValues = 1 [(.gogoproto.nullable) = false];</code>
     */
    public java.util.List<com.ai.procyon.grpc.common.ServiceProviderAttributeValue.Builder> 
         getServiceProviderAttributeValuesBuilderList() {
      return getServiceProviderAttributeValuesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ai.procyon.grpc.common.ServiceProviderAttributeValue, com.ai.procyon.grpc.common.ServiceProviderAttributeValue.Builder, com.ai.procyon.grpc.common.ServiceProviderAttributeValueOrBuilder> 
        getServiceProviderAttributeValuesFieldBuilder() {
      if (serviceProviderAttributeValuesBuilder_ == null) {
        serviceProviderAttributeValuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ai.procyon.grpc.common.ServiceProviderAttributeValue, com.ai.procyon.grpc.common.ServiceProviderAttributeValue.Builder, com.ai.procyon.grpc.common.ServiceProviderAttributeValueOrBuilder>(
                serviceProviderAttributeValues_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        serviceProviderAttributeValues_ = null;
      }
      return serviceProviderAttributeValuesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.ServiceProviderAttributeValueList)
  }

  // @@protoc_insertion_point(class_scope:model.ServiceProviderAttributeValueList)
  private static final com.ai.procyon.grpc.common.ServiceProviderAttributeValueList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ai.procyon.grpc.common.ServiceProviderAttributeValueList();
  }

  public static com.ai.procyon.grpc.common.ServiceProviderAttributeValueList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServiceProviderAttributeValueList>
      PARSER = new com.google.protobuf.AbstractParser<ServiceProviderAttributeValueList>() {
    @java.lang.Override
    public ServiceProviderAttributeValueList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServiceProviderAttributeValueList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServiceProviderAttributeValueList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServiceProviderAttributeValueList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ai.procyon.grpc.common.ServiceProviderAttributeValueList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

