// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

public interface ServiceAccountSpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.ServiceAccountSpec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string Type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>.model.GcpServiceAccountSpec GcpSpec = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"embedded;embedded_prefix:gcp_spec_&#92;""];</code>
   * @return Whether the gcpSpec field is set.
   */
  boolean hasGcpSpec();
  /**
   * <code>.model.GcpServiceAccountSpec GcpSpec = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"embedded;embedded_prefix:gcp_spec_&#92;""];</code>
   * @return The gcpSpec.
   */
  com.ai.procyon.grpc.common.GcpServiceAccountSpec getGcpSpec();
  /**
   * <code>.model.GcpServiceAccountSpec GcpSpec = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"embedded;embedded_prefix:gcp_spec_&#92;""];</code>
   */
  com.ai.procyon.grpc.common.GcpServiceAccountSpecOrBuilder getGcpSpecOrBuilder();

  /**
   * <code>.model.AwsServiceAccountSpec AwsSpec = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"embedded;embedded_prefix:aws_spec_&#92;""];</code>
   * @return Whether the awsSpec field is set.
   */
  boolean hasAwsSpec();
  /**
   * <code>.model.AwsServiceAccountSpec AwsSpec = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"embedded;embedded_prefix:aws_spec_&#92;""];</code>
   * @return The awsSpec.
   */
  com.ai.procyon.grpc.common.AwsServiceAccountSpec getAwsSpec();
  /**
   * <code>.model.AwsServiceAccountSpec AwsSpec = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"embedded;embedded_prefix:aws_spec_&#92;""];</code>
   */
  com.ai.procyon.grpc.common.AwsServiceAccountSpecOrBuilder getAwsSpecOrBuilder();

  /**
   * <code>string EncKey = 4;</code>
   * @return The encKey.
   */
  java.lang.String getEncKey();
  /**
   * <code>string EncKey = 4;</code>
   * @return The bytes for encKey.
   */
  com.google.protobuf.ByteString
      getEncKeyBytes();

  /**
   * <code>.model.AzureServiceAccountSpec AzureSpec = 5 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"embedded;embedded_prefix:azure_spec_&#92;""];</code>
   * @return Whether the azureSpec field is set.
   */
  boolean hasAzureSpec();
  /**
   * <code>.model.AzureServiceAccountSpec AzureSpec = 5 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"embedded;embedded_prefix:azure_spec_&#92;""];</code>
   * @return The azureSpec.
   */
  com.ai.procyon.grpc.common.AzureServiceAccountSpec getAzureSpec();
  /**
   * <code>.model.AzureServiceAccountSpec AzureSpec = 5 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "gorm:&#92;"embedded;embedded_prefix:azure_spec_&#92;""];</code>
   */
  com.ai.procyon.grpc.common.AzureServiceAccountSpecOrBuilder getAzureSpecOrBuilder();
}
