// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

public interface ServiceProviderAttributeValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.ServiceProviderAttributeValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string Type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string Value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string Value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>string InputType = 3 [(.validate.rules) = { ... }</code>
   * @return The inputType.
   */
  java.lang.String getInputType();
  /**
   * <code>string InputType = 3 [(.validate.rules) = { ... }</code>
   * @return The bytes for inputType.
   */
  com.google.protobuf.ByteString
      getInputTypeBytes();
}
