// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

public interface ServiceProviderAttributeListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.ServiceProviderAttributeList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .model.ServiceProviderAttribute ServiceProviderAttributes = 1 [(.gogoproto.nullable) = false];</code>
   */
  java.util.List<com.ai.procyon.grpc.common.ServiceProviderAttribute> 
      getServiceProviderAttributesList();
  /**
   * <code>repeated .model.ServiceProviderAttribute ServiceProviderAttributes = 1 [(.gogoproto.nullable) = false];</code>
   */
  com.ai.procyon.grpc.common.ServiceProviderAttribute getServiceProviderAttributes(int index);
  /**
   * <code>repeated .model.ServiceProviderAttribute ServiceProviderAttributes = 1 [(.gogoproto.nullable) = false];</code>
   */
  int getServiceProviderAttributesCount();
  /**
   * <code>repeated .model.ServiceProviderAttribute ServiceProviderAttributes = 1 [(.gogoproto.nullable) = false];</code>
   */
  java.util.List<? extends com.ai.procyon.grpc.common.ServiceProviderAttributeOrBuilder> 
      getServiceProviderAttributesOrBuilderList();
  /**
   * <code>repeated .model.ServiceProviderAttribute ServiceProviderAttributes = 1 [(.gogoproto.nullable) = false];</code>
   */
  com.ai.procyon.grpc.common.ServiceProviderAttributeOrBuilder getServiceProviderAttributesOrBuilder(
      int index);
}
