// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

/**
 * <pre>
 * custom string array type
 * </pre>
 *
 * Protobuf type {@code model.StringArray}
 */
public final class StringArray extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.StringArray)
    StringArrayOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StringArray.newBuilder() to construct.
  private StringArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StringArray() {
    elems_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StringArray();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StringArray(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              elems_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            elems_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        elems_ = elems_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ai.procyon.grpc.common.CommonProto.internal_static_model_StringArray_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ai.procyon.grpc.common.CommonProto.internal_static_model_StringArray_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ai.procyon.grpc.common.StringArray.class, com.ai.procyon.grpc.common.StringArray.Builder.class);
  }

  public static final int ELEMS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList elems_;
  /**
   * <code>repeated string Elems = 1;</code>
   * @return A list containing the elems.
   */
  public com.google.protobuf.ProtocolStringList
      getElemsList() {
    return elems_;
  }
  /**
   * <code>repeated string Elems = 1;</code>
   * @return The count of elems.
   */
  public int getElemsCount() {
    return elems_.size();
  }
  /**
   * <code>repeated string Elems = 1;</code>
   * @param index The index of the element to return.
   * @return The elems at the given index.
   */
  public java.lang.String getElems(int index) {
    return elems_.get(index);
  }
  /**
   * <code>repeated string Elems = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the elems at the given index.
   */
  public com.google.protobuf.ByteString
      getElemsBytes(int index) {
    return elems_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < elems_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, elems_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < elems_.size(); i++) {
        dataSize += computeStringSizeNoTag(elems_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getElemsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ai.procyon.grpc.common.StringArray)) {
      return super.equals(obj);
    }
    com.ai.procyon.grpc.common.StringArray other = (com.ai.procyon.grpc.common.StringArray) obj;

    if (!getElemsList()
        .equals(other.getElemsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getElemsCount() > 0) {
      hash = (37 * hash) + ELEMS_FIELD_NUMBER;
      hash = (53 * hash) + getElemsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ai.procyon.grpc.common.StringArray parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.StringArray parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.StringArray parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.StringArray parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.StringArray parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ai.procyon.grpc.common.StringArray parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.StringArray parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.StringArray parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.StringArray parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.StringArray parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ai.procyon.grpc.common.StringArray parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ai.procyon.grpc.common.StringArray parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ai.procyon.grpc.common.StringArray prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * custom string array type
   * </pre>
   *
   * Protobuf type {@code model.StringArray}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.StringArray)
      com.ai.procyon.grpc.common.StringArrayOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_StringArray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_StringArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ai.procyon.grpc.common.StringArray.class, com.ai.procyon.grpc.common.StringArray.Builder.class);
    }

    // Construct using com.ai.procyon.grpc.common.StringArray.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      elems_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ai.procyon.grpc.common.CommonProto.internal_static_model_StringArray_descriptor;
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.StringArray getDefaultInstanceForType() {
      return com.ai.procyon.grpc.common.StringArray.getDefaultInstance();
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.StringArray build() {
      com.ai.procyon.grpc.common.StringArray result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ai.procyon.grpc.common.StringArray buildPartial() {
      com.ai.procyon.grpc.common.StringArray result = new com.ai.procyon.grpc.common.StringArray(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        elems_ = elems_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.elems_ = elems_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ai.procyon.grpc.common.StringArray) {
        return mergeFrom((com.ai.procyon.grpc.common.StringArray)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ai.procyon.grpc.common.StringArray other) {
      if (other == com.ai.procyon.grpc.common.StringArray.getDefaultInstance()) return this;
      if (!other.elems_.isEmpty()) {
        if (elems_.isEmpty()) {
          elems_ = other.elems_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureElemsIsMutable();
          elems_.addAll(other.elems_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ai.procyon.grpc.common.StringArray parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ai.procyon.grpc.common.StringArray) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList elems_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureElemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        elems_ = new com.google.protobuf.LazyStringArrayList(elems_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string Elems = 1;</code>
     * @return A list containing the elems.
     */
    public com.google.protobuf.ProtocolStringList
        getElemsList() {
      return elems_.getUnmodifiableView();
    }
    /**
     * <code>repeated string Elems = 1;</code>
     * @return The count of elems.
     */
    public int getElemsCount() {
      return elems_.size();
    }
    /**
     * <code>repeated string Elems = 1;</code>
     * @param index The index of the element to return.
     * @return The elems at the given index.
     */
    public java.lang.String getElems(int index) {
      return elems_.get(index);
    }
    /**
     * <code>repeated string Elems = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the elems at the given index.
     */
    public com.google.protobuf.ByteString
        getElemsBytes(int index) {
      return elems_.getByteString(index);
    }
    /**
     * <code>repeated string Elems = 1;</code>
     * @param index The index to set the value at.
     * @param value The elems to set.
     * @return This builder for chaining.
     */
    public Builder setElems(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureElemsIsMutable();
      elems_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Elems = 1;</code>
     * @param value The elems to add.
     * @return This builder for chaining.
     */
    public Builder addElems(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureElemsIsMutable();
      elems_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Elems = 1;</code>
     * @param values The elems to add.
     * @return This builder for chaining.
     */
    public Builder addAllElems(
        java.lang.Iterable<java.lang.String> values) {
      ensureElemsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, elems_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Elems = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearElems() {
      elems_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Elems = 1;</code>
     * @param value The bytes of the elems to add.
     * @return This builder for chaining.
     */
    public Builder addElemsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureElemsIsMutable();
      elems_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.StringArray)
  }

  // @@protoc_insertion_point(class_scope:model.StringArray)
  private static final com.ai.procyon.grpc.common.StringArray DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ai.procyon.grpc.common.StringArray();
  }

  public static com.ai.procyon.grpc.common.StringArray getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StringArray>
      PARSER = new com.google.protobuf.AbstractParser<StringArray>() {
    @java.lang.Override
    public StringArray parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StringArray(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StringArray> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StringArray> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ai.procyon.grpc.common.StringArray getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

