// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ai.procyon.grpc.common;

public interface SubnetInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.SubnetInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string SubnetID = 1;</code>
   * @return The subnetID.
   */
  java.lang.String getSubnetID();
  /**
   * <code>string SubnetID = 1;</code>
   * @return The bytes for subnetID.
   */
  com.google.protobuf.ByteString
      getSubnetIDBytes();

  /**
   * <code>string Cidr = 2;</code>
   * @return The cidr.
   */
  java.lang.String getCidr();
  /**
   * <code>string Cidr = 2;</code>
   * @return The bytes for cidr.
   */
  com.google.protobuf.ByteString
      getCidrBytes();

  /**
   * <code>string TagName = 3;</code>
   * @return The tagName.
   */
  java.lang.String getTagName();
  /**
   * <code>string TagName = 3;</code>
   * @return The bytes for tagName.
   */
  com.google.protobuf.ByteString
      getTagNameBytes();
}
