// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notary.proto

package com.ai.procyon.grpc.rpc;

public interface DeviceTokenIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.DeviceTokenID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Device TokenID
   * </pre>
   *
   * <code>string DeviceTokenID = 1;</code>
   * @return The deviceTokenID.
   */
  String getDeviceTokenID();
  /**
   * <pre>
   * Device TokenID
   * </pre>
   *
   * <code>string DeviceTokenID = 1;</code>
   * @return The bytes for deviceTokenID.
   */
  com.google.protobuf.ByteString
      getDeviceTokenIDBytes();
}
