// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notary.proto

package com.ai.procyon.grpc.rpc;

public interface InfraCertRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.InfraCertResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * certificate (x509 pem)
   * </pre>
   *
   * <code>string Cert = 1;</code>
   * @return The cert.
   */
  String getCert();
  /**
   * <pre>
   * certificate (x509 pem)
   * </pre>
   *
   * <code>string Cert = 1;</code>
   * @return The bytes for cert.
   */
  com.google.protobuf.ByteString
      getCertBytes();

  /**
   * <pre>
   * key (pem)
   * </pre>
   *
   * <code>string Key = 2;</code>
   * @return The key.
   */
  String getKey();
  /**
   * <pre>
   * key (pem)
   * </pre>
   *
   * <code>string Key = 2;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <pre>
   * certchain (pem)
   * </pre>
   *
   * <code>string CertChain = 3;</code>
   * @return The certChain.
   */
  String getCertChain();
  /**
   * <pre>
   * certchain (pem)
   * </pre>
   *
   * <code>string CertChain = 3;</code>
   * @return The bytes for certChain.
   */
  com.google.protobuf.ByteString
      getCertChainBytes();
}
