// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notary.proto

package com.ai.procyon.grpc.rpc;

/**
 * Protobuf type {@code rpc.ProxyCertReq}
 */
public final class ProxyCertReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.ProxyCertReq)
    ProxyCertReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProxyCertReq.newBuilder() to construct.
  private ProxyCertReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProxyCertReq() {
    tokenID_ = "";
    encCSR_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProxyCertReq();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProxyCertReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            tokenID_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            encCSR_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RPCProto.internal_static_rpc_ProxyCertReq_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RPCProto.internal_static_rpc_ProxyCertReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ProxyCertReq.class, Builder.class);
  }

  public static final int TOKENID_FIELD_NUMBER = 1;
  private volatile Object tokenID_;
  /**
   * <pre>
   * Proxy Token ID
   * </pre>
   *
   * <code>string TokenID = 1;</code>
   * @return The tokenID.
   */
  @Override
  public String getTokenID() {
    Object ref = tokenID_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tokenID_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Proxy Token ID
   * </pre>
   *
   * <code>string TokenID = 1;</code>
   * @return The bytes for tokenID.
   */
  @Override
  public com.google.protobuf.ByteString
      getTokenIDBytes() {
    Object ref = tokenID_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tokenID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENCCSR_FIELD_NUMBER = 2;
  private volatile Object encCSR_;
  /**
   * <pre>
   * Encrypted CSR
   * </pre>
   *
   * <code>string EncCSR = 2;</code>
   * @return The encCSR.
   */
  @Override
  public String getEncCSR() {
    Object ref = encCSR_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      encCSR_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Encrypted CSR
   * </pre>
   *
   * <code>string EncCSR = 2;</code>
   * @return The bytes for encCSR.
   */
  @Override
  public com.google.protobuf.ByteString
      getEncCSRBytes() {
    Object ref = encCSR_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      encCSR_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTokenIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tokenID_);
    }
    if (!getEncCSRBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, encCSR_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTokenIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tokenID_);
    }
    if (!getEncCSRBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, encCSR_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ProxyCertReq)) {
      return super.equals(obj);
    }
    ProxyCertReq other = (ProxyCertReq) obj;

    if (!getTokenID()
        .equals(other.getTokenID())) return false;
    if (!getEncCSR()
        .equals(other.getEncCSR())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOKENID_FIELD_NUMBER;
    hash = (53 * hash) + getTokenID().hashCode();
    hash = (37 * hash) + ENCCSR_FIELD_NUMBER;
    hash = (53 * hash) + getEncCSR().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ProxyCertReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProxyCertReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProxyCertReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProxyCertReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProxyCertReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProxyCertReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProxyCertReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ProxyCertReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ProxyCertReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ProxyCertReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ProxyCertReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ProxyCertReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ProxyCertReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.ProxyCertReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.ProxyCertReq)
      ProxyCertReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RPCProto.internal_static_rpc_ProxyCertReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RPCProto.internal_static_rpc_ProxyCertReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProxyCertReq.class, Builder.class);
    }

    // Construct using com.ai.procyon.grpc.rpc.ProxyCertReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      tokenID_ = "";

      encCSR_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RPCProto.internal_static_rpc_ProxyCertReq_descriptor;
    }

    @Override
    public ProxyCertReq getDefaultInstanceForType() {
      return ProxyCertReq.getDefaultInstance();
    }

    @Override
    public ProxyCertReq build() {
      ProxyCertReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ProxyCertReq buildPartial() {
      ProxyCertReq result = new ProxyCertReq(this);
      result.tokenID_ = tokenID_;
      result.encCSR_ = encCSR_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ProxyCertReq) {
        return mergeFrom((ProxyCertReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ProxyCertReq other) {
      if (other == ProxyCertReq.getDefaultInstance()) return this;
      if (!other.getTokenID().isEmpty()) {
        tokenID_ = other.tokenID_;
        onChanged();
      }
      if (!other.getEncCSR().isEmpty()) {
        encCSR_ = other.encCSR_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ProxyCertReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ProxyCertReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object tokenID_ = "";
    /**
     * <pre>
     * Proxy Token ID
     * </pre>
     *
     * <code>string TokenID = 1;</code>
     * @return The tokenID.
     */
    public String getTokenID() {
      Object ref = tokenID_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tokenID_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Proxy Token ID
     * </pre>
     *
     * <code>string TokenID = 1;</code>
     * @return The bytes for tokenID.
     */
    public com.google.protobuf.ByteString
        getTokenIDBytes() {
      Object ref = tokenID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tokenID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Proxy Token ID
     * </pre>
     *
     * <code>string TokenID = 1;</code>
     * @param value The tokenID to set.
     * @return This builder for chaining.
     */
    public Builder setTokenID(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tokenID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Proxy Token ID
     * </pre>
     *
     * <code>string TokenID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTokenID() {
      
      tokenID_ = getDefaultInstance().getTokenID();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Proxy Token ID
     * </pre>
     *
     * <code>string TokenID = 1;</code>
     * @param value The bytes for tokenID to set.
     * @return This builder for chaining.
     */
    public Builder setTokenIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tokenID_ = value;
      onChanged();
      return this;
    }

    private Object encCSR_ = "";
    /**
     * <pre>
     * Encrypted CSR
     * </pre>
     *
     * <code>string EncCSR = 2;</code>
     * @return The encCSR.
     */
    public String getEncCSR() {
      Object ref = encCSR_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        encCSR_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Encrypted CSR
     * </pre>
     *
     * <code>string EncCSR = 2;</code>
     * @return The bytes for encCSR.
     */
    public com.google.protobuf.ByteString
        getEncCSRBytes() {
      Object ref = encCSR_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        encCSR_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Encrypted CSR
     * </pre>
     *
     * <code>string EncCSR = 2;</code>
     * @param value The encCSR to set.
     * @return This builder for chaining.
     */
    public Builder setEncCSR(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      encCSR_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Encrypted CSR
     * </pre>
     *
     * <code>string EncCSR = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncCSR() {
      
      encCSR_ = getDefaultInstance().getEncCSR();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Encrypted CSR
     * </pre>
     *
     * <code>string EncCSR = 2;</code>
     * @param value The bytes for encCSR to set.
     * @return This builder for chaining.
     */
    public Builder setEncCSRBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      encCSR_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.ProxyCertReq)
  }

  // @@protoc_insertion_point(class_scope:rpc.ProxyCertReq)
  private static final ProxyCertReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ProxyCertReq();
  }

  public static ProxyCertReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProxyCertReq>
      PARSER = new com.google.protobuf.AbstractParser<ProxyCertReq>() {
    @Override
    public ProxyCertReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProxyCertReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProxyCertReq> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ProxyCertReq> getParserForType() {
    return PARSER;
  }

  @Override
  public ProxyCertReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

