// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notary.proto

package com.ai.procyon.grpc.rpc;

public interface ProxyTokenRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.ProxyTokenResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Proxy Token (base64 encoded metadata)
   * </pre>
   *
   * <code>string ProxyToken = 1;</code>
   * @return The proxyToken.
   */
  String getProxyToken();
  /**
   * <pre>
   * Proxy Token (base64 encoded metadata)
   * </pre>
   *
   * <code>string ProxyToken = 1;</code>
   * @return The bytes for proxyToken.
   */
  com.google.protobuf.ByteString
      getProxyTokenBytes();
}
