// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notary.proto

package com.ai.procyon.grpc.rpc;

public interface SignRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.SignResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * type of certificate (x509 or ssh)
   * </pre>
   *
   * <code>string CertType = 1;</code>
   * @return The certType.
   */
  String getCertType();
  /**
   * <pre>
   * type of certificate (x509 or ssh)
   * </pre>
   *
   * <code>string CertType = 1;</code>
   * @return The bytes for certType.
   */
  com.google.protobuf.ByteString
      getCertTypeBytes();

  /**
   * <pre>
   * issued certificate
   * </pre>
   *
   * <code>string Certificate = 2;</code>
   * @return The certificate.
   */
  String getCertificate();
  /**
   * <pre>
   * issued certificate
   * </pre>
   *
   * <code>string Certificate = 2;</code>
   * @return The bytes for certificate.
   */
  com.google.protobuf.ByteString
      getCertificateBytes();

  /**
   * <pre>
   * infra intermediate cert
   * </pre>
   *
   * <code>string InfraInterCert = 3;</code>
   * @return The infraInterCert.
   */
  String getInfraInterCert();
  /**
   * <pre>
   * infra intermediate cert
   * </pre>
   *
   * <code>string InfraInterCert = 3;</code>
   * @return The bytes for infraInterCert.
   */
  com.google.protobuf.ByteString
      getInfraInterCertBytes();
}
