// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notary.proto

package com.ai.procyon.grpc.rpc;

/**
 * Protobuf type {@code rpc.TargetCertReq}
 */
public final class TargetCertReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.TargetCertReq)
    TargetCertReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TargetCertReq.newBuilder() to construct.
  private TargetCertReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TargetCertReq() {
    aPIKey_ = "";
    encCSR_ = "";
    clusterID_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TargetCertReq();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TargetCertReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            aPIKey_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            encCSR_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            clusterID_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RPCProto.internal_static_rpc_TargetCertReq_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RPCProto.internal_static_rpc_TargetCertReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TargetCertReq.class, Builder.class);
  }

  public static final int APIKEY_FIELD_NUMBER = 1;
  private volatile Object aPIKey_;
  /**
   * <pre>
   * APIKey
   * </pre>
   *
   * <code>string APIKey = 1;</code>
   * @return The aPIKey.
   */
  @Override
  public String getAPIKey() {
    Object ref = aPIKey_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      aPIKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * APIKey
   * </pre>
   *
   * <code>string APIKey = 1;</code>
   * @return The bytes for aPIKey.
   */
  @Override
  public com.google.protobuf.ByteString
      getAPIKeyBytes() {
    Object ref = aPIKey_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      aPIKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENCCSR_FIELD_NUMBER = 2;
  private volatile Object encCSR_;
  /**
   * <pre>
   * Encrypted CSR
   * </pre>
   *
   * <code>string EncCSR = 2;</code>
   * @return The encCSR.
   */
  @Override
  public String getEncCSR() {
    Object ref = encCSR_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      encCSR_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Encrypted CSR
   * </pre>
   *
   * <code>string EncCSR = 2;</code>
   * @return The bytes for encCSR.
   */
  @Override
  public com.google.protobuf.ByteString
      getEncCSRBytes() {
    Object ref = encCSR_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      encCSR_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLUSTERID_FIELD_NUMBER = 3;
  private volatile Object clusterID_;
  /**
   * <pre>
   * ClusterId
   * </pre>
   *
   * <code>string ClusterID = 3;</code>
   * @return The clusterID.
   */
  @Override
  public String getClusterID() {
    Object ref = clusterID_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      clusterID_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ClusterId
   * </pre>
   *
   * <code>string ClusterID = 3;</code>
   * @return The bytes for clusterID.
   */
  @Override
  public com.google.protobuf.ByteString
      getClusterIDBytes() {
    Object ref = clusterID_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      clusterID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAPIKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, aPIKey_);
    }
    if (!getEncCSRBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, encCSR_);
    }
    if (!getClusterIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clusterID_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAPIKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, aPIKey_);
    }
    if (!getEncCSRBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, encCSR_);
    }
    if (!getClusterIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clusterID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TargetCertReq)) {
      return super.equals(obj);
    }
    TargetCertReq other = (TargetCertReq) obj;

    if (!getAPIKey()
        .equals(other.getAPIKey())) return false;
    if (!getEncCSR()
        .equals(other.getEncCSR())) return false;
    if (!getClusterID()
        .equals(other.getClusterID())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APIKEY_FIELD_NUMBER;
    hash = (53 * hash) + getAPIKey().hashCode();
    hash = (37 * hash) + ENCCSR_FIELD_NUMBER;
    hash = (53 * hash) + getEncCSR().hashCode();
    hash = (37 * hash) + CLUSTERID_FIELD_NUMBER;
    hash = (53 * hash) + getClusterID().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TargetCertReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TargetCertReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TargetCertReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TargetCertReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TargetCertReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TargetCertReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TargetCertReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TargetCertReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TargetCertReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TargetCertReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TargetCertReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TargetCertReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TargetCertReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.TargetCertReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.TargetCertReq)
      TargetCertReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RPCProto.internal_static_rpc_TargetCertReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RPCProto.internal_static_rpc_TargetCertReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TargetCertReq.class, Builder.class);
    }

    // Construct using com.ai.procyon.grpc.rpc.TargetCertReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      aPIKey_ = "";

      encCSR_ = "";

      clusterID_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RPCProto.internal_static_rpc_TargetCertReq_descriptor;
    }

    @Override
    public TargetCertReq getDefaultInstanceForType() {
      return TargetCertReq.getDefaultInstance();
    }

    @Override
    public TargetCertReq build() {
      TargetCertReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TargetCertReq buildPartial() {
      TargetCertReq result = new TargetCertReq(this);
      result.aPIKey_ = aPIKey_;
      result.encCSR_ = encCSR_;
      result.clusterID_ = clusterID_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TargetCertReq) {
        return mergeFrom((TargetCertReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TargetCertReq other) {
      if (other == TargetCertReq.getDefaultInstance()) return this;
      if (!other.getAPIKey().isEmpty()) {
        aPIKey_ = other.aPIKey_;
        onChanged();
      }
      if (!other.getEncCSR().isEmpty()) {
        encCSR_ = other.encCSR_;
        onChanged();
      }
      if (!other.getClusterID().isEmpty()) {
        clusterID_ = other.clusterID_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TargetCertReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TargetCertReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object aPIKey_ = "";
    /**
     * <pre>
     * APIKey
     * </pre>
     *
     * <code>string APIKey = 1;</code>
     * @return The aPIKey.
     */
    public String getAPIKey() {
      Object ref = aPIKey_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        aPIKey_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * APIKey
     * </pre>
     *
     * <code>string APIKey = 1;</code>
     * @return The bytes for aPIKey.
     */
    public com.google.protobuf.ByteString
        getAPIKeyBytes() {
      Object ref = aPIKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        aPIKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * APIKey
     * </pre>
     *
     * <code>string APIKey = 1;</code>
     * @param value The aPIKey to set.
     * @return This builder for chaining.
     */
    public Builder setAPIKey(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aPIKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * APIKey
     * </pre>
     *
     * <code>string APIKey = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAPIKey() {
      
      aPIKey_ = getDefaultInstance().getAPIKey();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * APIKey
     * </pre>
     *
     * <code>string APIKey = 1;</code>
     * @param value The bytes for aPIKey to set.
     * @return This builder for chaining.
     */
    public Builder setAPIKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aPIKey_ = value;
      onChanged();
      return this;
    }

    private Object encCSR_ = "";
    /**
     * <pre>
     * Encrypted CSR
     * </pre>
     *
     * <code>string EncCSR = 2;</code>
     * @return The encCSR.
     */
    public String getEncCSR() {
      Object ref = encCSR_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        encCSR_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Encrypted CSR
     * </pre>
     *
     * <code>string EncCSR = 2;</code>
     * @return The bytes for encCSR.
     */
    public com.google.protobuf.ByteString
        getEncCSRBytes() {
      Object ref = encCSR_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        encCSR_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Encrypted CSR
     * </pre>
     *
     * <code>string EncCSR = 2;</code>
     * @param value The encCSR to set.
     * @return This builder for chaining.
     */
    public Builder setEncCSR(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      encCSR_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Encrypted CSR
     * </pre>
     *
     * <code>string EncCSR = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncCSR() {
      
      encCSR_ = getDefaultInstance().getEncCSR();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Encrypted CSR
     * </pre>
     *
     * <code>string EncCSR = 2;</code>
     * @param value The bytes for encCSR to set.
     * @return This builder for chaining.
     */
    public Builder setEncCSRBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      encCSR_ = value;
      onChanged();
      return this;
    }

    private Object clusterID_ = "";
    /**
     * <pre>
     * ClusterId
     * </pre>
     *
     * <code>string ClusterID = 3;</code>
     * @return The clusterID.
     */
    public String getClusterID() {
      Object ref = clusterID_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clusterID_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * ClusterId
     * </pre>
     *
     * <code>string ClusterID = 3;</code>
     * @return The bytes for clusterID.
     */
    public com.google.protobuf.ByteString
        getClusterIDBytes() {
      Object ref = clusterID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clusterID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ClusterId
     * </pre>
     *
     * <code>string ClusterID = 3;</code>
     * @param value The clusterID to set.
     * @return This builder for chaining.
     */
    public Builder setClusterID(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clusterID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ClusterId
     * </pre>
     *
     * <code>string ClusterID = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearClusterID() {
      
      clusterID_ = getDefaultInstance().getClusterID();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ClusterId
     * </pre>
     *
     * <code>string ClusterID = 3;</code>
     * @param value The bytes for clusterID to set.
     * @return This builder for chaining.
     */
    public Builder setClusterIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clusterID_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.TargetCertReq)
  }

  // @@protoc_insertion_point(class_scope:rpc.TargetCertReq)
  private static final TargetCertReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TargetCertReq();
  }

  public static TargetCertReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TargetCertReq>
      PARSER = new com.google.protobuf.AbstractParser<TargetCertReq>() {
    @Override
    public TargetCertReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TargetCertReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TargetCertReq> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TargetCertReq> getParserForType() {
    return PARSER;
  }

  @Override
  public TargetCertReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

