// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notary.proto

package com.ai.procyon.grpc.rpc;

/**
 * Protobuf type {@code rpc.TargetCertRes}
 */
public final class TargetCertRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.TargetCertRes)
    TargetCertResOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TargetCertRes.newBuilder() to construct.
  private TargetCertRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TargetCertRes() {
    cert_ = "";
    certChain_ = "";
    tenantRoot_ = "";
    token_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TargetCertRes();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TargetCertRes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            cert_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            certChain_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            tenantRoot_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            token_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RPCProto.internal_static_rpc_TargetCertRes_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RPCProto.internal_static_rpc_TargetCertRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TargetCertRes.class, Builder.class);
  }

  public static final int CERT_FIELD_NUMBER = 1;
  private volatile Object cert_;
  /**
   * <pre>
   * certificate (x509 pem)
   * </pre>
   *
   * <code>string Cert = 1;</code>
   * @return The cert.
   */
  @Override
  public String getCert() {
    Object ref = cert_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      cert_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * certificate (x509 pem)
   * </pre>
   *
   * <code>string Cert = 1;</code>
   * @return The bytes for cert.
   */
  @Override
  public com.google.protobuf.ByteString
      getCertBytes() {
    Object ref = cert_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      cert_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CERTCHAIN_FIELD_NUMBER = 2;
  private volatile Object certChain_;
  /**
   * <pre>
   * certchain (pem)
   * </pre>
   *
   * <code>string CertChain = 2;</code>
   * @return The certChain.
   */
  @Override
  public String getCertChain() {
    Object ref = certChain_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      certChain_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * certchain (pem)
   * </pre>
   *
   * <code>string CertChain = 2;</code>
   * @return The bytes for certChain.
   */
  @Override
  public com.google.protobuf.ByteString
      getCertChainBytes() {
    Object ref = certChain_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      certChain_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANTROOT_FIELD_NUMBER = 3;
  private volatile Object tenantRoot_;
  /**
   * <pre>
   * tenant root ca (pem)
   * </pre>
   *
   * <code>string TenantRoot = 3;</code>
   * @return The tenantRoot.
   */
  @Override
  public String getTenantRoot() {
    Object ref = tenantRoot_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tenantRoot_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * tenant root ca (pem)
   * </pre>
   *
   * <code>string TenantRoot = 3;</code>
   * @return The bytes for tenantRoot.
   */
  @Override
  public com.google.protobuf.ByteString
      getTenantRootBytes() {
    Object ref = tenantRoot_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tenantRoot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKEN_FIELD_NUMBER = 4;
  private volatile Object token_;
  /**
   * <pre>
   * token file
   * </pre>
   *
   * <code>string Token = 4;</code>
   * @return The token.
   */
  @Override
  public String getToken() {
    Object ref = token_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * token file
   * </pre>
   *
   * <code>string Token = 4;</code>
   * @return The bytes for token.
   */
  @Override
  public com.google.protobuf.ByteString
      getTokenBytes() {
    Object ref = token_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCertBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cert_);
    }
    if (!getCertChainBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, certChain_);
    }
    if (!getTenantRootBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tenantRoot_);
    }
    if (!getTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, token_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCertBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cert_);
    }
    if (!getCertChainBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, certChain_);
    }
    if (!getTenantRootBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tenantRoot_);
    }
    if (!getTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, token_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TargetCertRes)) {
      return super.equals(obj);
    }
    TargetCertRes other = (TargetCertRes) obj;

    if (!getCert()
        .equals(other.getCert())) return false;
    if (!getCertChain()
        .equals(other.getCertChain())) return false;
    if (!getTenantRoot()
        .equals(other.getTenantRoot())) return false;
    if (!getToken()
        .equals(other.getToken())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CERT_FIELD_NUMBER;
    hash = (53 * hash) + getCert().hashCode();
    hash = (37 * hash) + CERTCHAIN_FIELD_NUMBER;
    hash = (53 * hash) + getCertChain().hashCode();
    hash = (37 * hash) + TENANTROOT_FIELD_NUMBER;
    hash = (53 * hash) + getTenantRoot().hashCode();
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TargetCertRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TargetCertRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TargetCertRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TargetCertRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TargetCertRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TargetCertRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TargetCertRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TargetCertRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TargetCertRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TargetCertRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TargetCertRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TargetCertRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TargetCertRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.TargetCertRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.TargetCertRes)
      TargetCertResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RPCProto.internal_static_rpc_TargetCertRes_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RPCProto.internal_static_rpc_TargetCertRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TargetCertRes.class, Builder.class);
    }

    // Construct using com.ai.procyon.grpc.rpc.TargetCertRes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      cert_ = "";

      certChain_ = "";

      tenantRoot_ = "";

      token_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RPCProto.internal_static_rpc_TargetCertRes_descriptor;
    }

    @Override
    public TargetCertRes getDefaultInstanceForType() {
      return TargetCertRes.getDefaultInstance();
    }

    @Override
    public TargetCertRes build() {
      TargetCertRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TargetCertRes buildPartial() {
      TargetCertRes result = new TargetCertRes(this);
      result.cert_ = cert_;
      result.certChain_ = certChain_;
      result.tenantRoot_ = tenantRoot_;
      result.token_ = token_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TargetCertRes) {
        return mergeFrom((TargetCertRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TargetCertRes other) {
      if (other == TargetCertRes.getDefaultInstance()) return this;
      if (!other.getCert().isEmpty()) {
        cert_ = other.cert_;
        onChanged();
      }
      if (!other.getCertChain().isEmpty()) {
        certChain_ = other.certChain_;
        onChanged();
      }
      if (!other.getTenantRoot().isEmpty()) {
        tenantRoot_ = other.tenantRoot_;
        onChanged();
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TargetCertRes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TargetCertRes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object cert_ = "";
    /**
     * <pre>
     * certificate (x509 pem)
     * </pre>
     *
     * <code>string Cert = 1;</code>
     * @return The cert.
     */
    public String getCert() {
      Object ref = cert_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cert_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * certificate (x509 pem)
     * </pre>
     *
     * <code>string Cert = 1;</code>
     * @return The bytes for cert.
     */
    public com.google.protobuf.ByteString
        getCertBytes() {
      Object ref = cert_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cert_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * certificate (x509 pem)
     * </pre>
     *
     * <code>string Cert = 1;</code>
     * @param value The cert to set.
     * @return This builder for chaining.
     */
    public Builder setCert(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cert_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * certificate (x509 pem)
     * </pre>
     *
     * <code>string Cert = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCert() {
      
      cert_ = getDefaultInstance().getCert();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * certificate (x509 pem)
     * </pre>
     *
     * <code>string Cert = 1;</code>
     * @param value The bytes for cert to set.
     * @return This builder for chaining.
     */
    public Builder setCertBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cert_ = value;
      onChanged();
      return this;
    }

    private Object certChain_ = "";
    /**
     * <pre>
     * certchain (pem)
     * </pre>
     *
     * <code>string CertChain = 2;</code>
     * @return The certChain.
     */
    public String getCertChain() {
      Object ref = certChain_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        certChain_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * certchain (pem)
     * </pre>
     *
     * <code>string CertChain = 2;</code>
     * @return The bytes for certChain.
     */
    public com.google.protobuf.ByteString
        getCertChainBytes() {
      Object ref = certChain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        certChain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * certchain (pem)
     * </pre>
     *
     * <code>string CertChain = 2;</code>
     * @param value The certChain to set.
     * @return This builder for chaining.
     */
    public Builder setCertChain(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      certChain_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * certchain (pem)
     * </pre>
     *
     * <code>string CertChain = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCertChain() {
      
      certChain_ = getDefaultInstance().getCertChain();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * certchain (pem)
     * </pre>
     *
     * <code>string CertChain = 2;</code>
     * @param value The bytes for certChain to set.
     * @return This builder for chaining.
     */
    public Builder setCertChainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      certChain_ = value;
      onChanged();
      return this;
    }

    private Object tenantRoot_ = "";
    /**
     * <pre>
     * tenant root ca (pem)
     * </pre>
     *
     * <code>string TenantRoot = 3;</code>
     * @return The tenantRoot.
     */
    public String getTenantRoot() {
      Object ref = tenantRoot_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tenantRoot_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * tenant root ca (pem)
     * </pre>
     *
     * <code>string TenantRoot = 3;</code>
     * @return The bytes for tenantRoot.
     */
    public com.google.protobuf.ByteString
        getTenantRootBytes() {
      Object ref = tenantRoot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tenantRoot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * tenant root ca (pem)
     * </pre>
     *
     * <code>string TenantRoot = 3;</code>
     * @param value The tenantRoot to set.
     * @return This builder for chaining.
     */
    public Builder setTenantRoot(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tenantRoot_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * tenant root ca (pem)
     * </pre>
     *
     * <code>string TenantRoot = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantRoot() {
      
      tenantRoot_ = getDefaultInstance().getTenantRoot();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * tenant root ca (pem)
     * </pre>
     *
     * <code>string TenantRoot = 3;</code>
     * @param value The bytes for tenantRoot to set.
     * @return This builder for chaining.
     */
    public Builder setTenantRootBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tenantRoot_ = value;
      onChanged();
      return this;
    }

    private Object token_ = "";
    /**
     * <pre>
     * token file
     * </pre>
     *
     * <code>string Token = 4;</code>
     * @return The token.
     */
    public String getToken() {
      Object ref = token_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * token file
     * </pre>
     *
     * <code>string Token = 4;</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * token file
     * </pre>
     *
     * <code>string Token = 4;</code>
     * @param value The token to set.
     * @return This builder for chaining.
     */
    public Builder setToken(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * token file
     * </pre>
     *
     * <code>string Token = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * token file
     * </pre>
     *
     * <code>string Token = 4;</code>
     * @param value The bytes for token to set.
     * @return This builder for chaining.
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      token_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.TargetCertRes)
  }

  // @@protoc_insertion_point(class_scope:rpc.TargetCertRes)
  private static final TargetCertRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TargetCertRes();
  }

  public static TargetCertRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TargetCertRes>
      PARSER = new com.google.protobuf.AbstractParser<TargetCertRes>() {
    @Override
    public TargetCertRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TargetCertRes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TargetCertRes> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TargetCertRes> getParserForType() {
    return PARSER;
  }

  @Override
  public TargetCertRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

