// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notary.proto

package com.ai.procyon.grpc.rpc;

public interface TargetCertReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.TargetCertReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * APIKey
   * </pre>
   *
   * <code>string APIKey = 1;</code>
   * @return The aPIKey.
   */
  String getAPIKey();
  /**
   * <pre>
   * APIKey
   * </pre>
   *
   * <code>string APIKey = 1;</code>
   * @return The bytes for aPIKey.
   */
  com.google.protobuf.ByteString
      getAPIKeyBytes();

  /**
   * <pre>
   * Encrypted CSR
   * </pre>
   *
   * <code>string EncCSR = 2;</code>
   * @return The encCSR.
   */
  String getEncCSR();
  /**
   * <pre>
   * Encrypted CSR
   * </pre>
   *
   * <code>string EncCSR = 2;</code>
   * @return The bytes for encCSR.
   */
  com.google.protobuf.ByteString
      getEncCSRBytes();

  /**
   * <pre>
   * ClusterId
   * </pre>
   *
   * <code>string ClusterID = 3;</code>
   * @return The clusterID.
   */
  String getClusterID();
  /**
   * <pre>
   * ClusterId
   * </pre>
   *
   * <code>string ClusterID = 3;</code>
   * @return The bytes for clusterID.
   */
  com.google.protobuf.ByteString
      getClusterIDBytes();
}
